
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Discipline: 'Discipline',
  SchoolDiscipline: 'SchoolDiscipline',
  School: 'School',
  Instructor: 'Instructor',
  MembershipPlan: 'MembershipPlan',
  Review: 'Review',
  Class: 'Class',
  Booking: 'Booking',
  Membership: 'Membership',
  Camp: 'Camp',
  CampBooking: 'CampBooking',
  SchoolMember: 'SchoolMember',
  SchoolClaim: 'SchoolClaim',
  Partner: 'Partner'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "discipline" | "schoolDiscipline" | "school" | "instructor" | "membershipPlan" | "review" | "class" | "booking" | "membership" | "camp" | "campBooking" | "schoolMember" | "schoolClaim" | "partner"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Discipline: {
      payload: Prisma.$DisciplinePayload<ExtArgs>
      fields: Prisma.DisciplineFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DisciplineFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DisciplineFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>
        }
        findFirst: {
          args: Prisma.DisciplineFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DisciplineFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>
        }
        findMany: {
          args: Prisma.DisciplineFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>[]
        }
        create: {
          args: Prisma.DisciplineCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>
        }
        createMany: {
          args: Prisma.DisciplineCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DisciplineCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>[]
        }
        delete: {
          args: Prisma.DisciplineDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>
        }
        update: {
          args: Prisma.DisciplineUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>
        }
        deleteMany: {
          args: Prisma.DisciplineDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DisciplineUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DisciplineUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>[]
        }
        upsert: {
          args: Prisma.DisciplineUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DisciplinePayload>
        }
        aggregate: {
          args: Prisma.DisciplineAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDiscipline>
        }
        groupBy: {
          args: Prisma.DisciplineGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DisciplineGroupByOutputType>[]
        }
        count: {
          args: Prisma.DisciplineCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DisciplineCountAggregateOutputType> | number
        }
      }
    }
    SchoolDiscipline: {
      payload: Prisma.$SchoolDisciplinePayload<ExtArgs>
      fields: Prisma.SchoolDisciplineFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SchoolDisciplineFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SchoolDisciplineFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>
        }
        findFirst: {
          args: Prisma.SchoolDisciplineFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SchoolDisciplineFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>
        }
        findMany: {
          args: Prisma.SchoolDisciplineFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>[]
        }
        create: {
          args: Prisma.SchoolDisciplineCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>
        }
        createMany: {
          args: Prisma.SchoolDisciplineCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SchoolDisciplineCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>[]
        }
        delete: {
          args: Prisma.SchoolDisciplineDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>
        }
        update: {
          args: Prisma.SchoolDisciplineUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>
        }
        deleteMany: {
          args: Prisma.SchoolDisciplineDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SchoolDisciplineUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SchoolDisciplineUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>[]
        }
        upsert: {
          args: Prisma.SchoolDisciplineUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolDisciplinePayload>
        }
        aggregate: {
          args: Prisma.SchoolDisciplineAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSchoolDiscipline>
        }
        groupBy: {
          args: Prisma.SchoolDisciplineGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SchoolDisciplineGroupByOutputType>[]
        }
        count: {
          args: Prisma.SchoolDisciplineCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SchoolDisciplineCountAggregateOutputType> | number
        }
      }
    }
    School: {
      payload: Prisma.$SchoolPayload<ExtArgs>
      fields: Prisma.SchoolFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SchoolFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SchoolFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>
        }
        findFirst: {
          args: Prisma.SchoolFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SchoolFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>
        }
        findMany: {
          args: Prisma.SchoolFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>[]
        }
        create: {
          args: Prisma.SchoolCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>
        }
        createMany: {
          args: Prisma.SchoolCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SchoolCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>[]
        }
        delete: {
          args: Prisma.SchoolDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>
        }
        update: {
          args: Prisma.SchoolUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>
        }
        deleteMany: {
          args: Prisma.SchoolDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SchoolUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SchoolUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>[]
        }
        upsert: {
          args: Prisma.SchoolUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolPayload>
        }
        aggregate: {
          args: Prisma.SchoolAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSchool>
        }
        groupBy: {
          args: Prisma.SchoolGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SchoolGroupByOutputType>[]
        }
        count: {
          args: Prisma.SchoolCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SchoolCountAggregateOutputType> | number
        }
      }
    }
    Instructor: {
      payload: Prisma.$InstructorPayload<ExtArgs>
      fields: Prisma.InstructorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.InstructorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.InstructorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>
        }
        findFirst: {
          args: Prisma.InstructorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.InstructorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>
        }
        findMany: {
          args: Prisma.InstructorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>[]
        }
        create: {
          args: Prisma.InstructorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>
        }
        createMany: {
          args: Prisma.InstructorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.InstructorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>[]
        }
        delete: {
          args: Prisma.InstructorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>
        }
        update: {
          args: Prisma.InstructorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>
        }
        deleteMany: {
          args: Prisma.InstructorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.InstructorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.InstructorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>[]
        }
        upsert: {
          args: Prisma.InstructorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InstructorPayload>
        }
        aggregate: {
          args: Prisma.InstructorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInstructor>
        }
        groupBy: {
          args: Prisma.InstructorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InstructorGroupByOutputType>[]
        }
        count: {
          args: Prisma.InstructorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InstructorCountAggregateOutputType> | number
        }
      }
    }
    MembershipPlan: {
      payload: Prisma.$MembershipPlanPayload<ExtArgs>
      fields: Prisma.MembershipPlanFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MembershipPlanFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MembershipPlanFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>
        }
        findFirst: {
          args: Prisma.MembershipPlanFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MembershipPlanFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>
        }
        findMany: {
          args: Prisma.MembershipPlanFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>[]
        }
        create: {
          args: Prisma.MembershipPlanCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>
        }
        createMany: {
          args: Prisma.MembershipPlanCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MembershipPlanCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>[]
        }
        delete: {
          args: Prisma.MembershipPlanDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>
        }
        update: {
          args: Prisma.MembershipPlanUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>
        }
        deleteMany: {
          args: Prisma.MembershipPlanDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MembershipPlanUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MembershipPlanUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>[]
        }
        upsert: {
          args: Prisma.MembershipPlanUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPlanPayload>
        }
        aggregate: {
          args: Prisma.MembershipPlanAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMembershipPlan>
        }
        groupBy: {
          args: Prisma.MembershipPlanGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MembershipPlanGroupByOutputType>[]
        }
        count: {
          args: Prisma.MembershipPlanCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MembershipPlanCountAggregateOutputType> | number
        }
      }
    }
    Review: {
      payload: Prisma.$ReviewPayload<ExtArgs>
      fields: Prisma.ReviewFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ReviewFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ReviewFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>
        }
        findFirst: {
          args: Prisma.ReviewFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ReviewFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>
        }
        findMany: {
          args: Prisma.ReviewFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>[]
        }
        create: {
          args: Prisma.ReviewCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>
        }
        createMany: {
          args: Prisma.ReviewCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ReviewCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>[]
        }
        delete: {
          args: Prisma.ReviewDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>
        }
        update: {
          args: Prisma.ReviewUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>
        }
        deleteMany: {
          args: Prisma.ReviewDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ReviewUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ReviewUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>[]
        }
        upsert: {
          args: Prisma.ReviewUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReviewPayload>
        }
        aggregate: {
          args: Prisma.ReviewAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateReview>
        }
        groupBy: {
          args: Prisma.ReviewGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReviewGroupByOutputType>[]
        }
        count: {
          args: Prisma.ReviewCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReviewCountAggregateOutputType> | number
        }
      }
    }
    Class: {
      payload: Prisma.$ClassPayload<ExtArgs>
      fields: Prisma.ClassFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ClassFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ClassFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>
        }
        findFirst: {
          args: Prisma.ClassFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ClassFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>
        }
        findMany: {
          args: Prisma.ClassFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>[]
        }
        create: {
          args: Prisma.ClassCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>
        }
        createMany: {
          args: Prisma.ClassCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ClassCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>[]
        }
        delete: {
          args: Prisma.ClassDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>
        }
        update: {
          args: Prisma.ClassUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>
        }
        deleteMany: {
          args: Prisma.ClassDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ClassUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ClassUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>[]
        }
        upsert: {
          args: Prisma.ClassUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClassPayload>
        }
        aggregate: {
          args: Prisma.ClassAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateClass>
        }
        groupBy: {
          args: Prisma.ClassGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClassGroupByOutputType>[]
        }
        count: {
          args: Prisma.ClassCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClassCountAggregateOutputType> | number
        }
      }
    }
    Booking: {
      payload: Prisma.$BookingPayload<ExtArgs>
      fields: Prisma.BookingFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BookingFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BookingFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>
        }
        findFirst: {
          args: Prisma.BookingFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BookingFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>
        }
        findMany: {
          args: Prisma.BookingFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>[]
        }
        create: {
          args: Prisma.BookingCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>
        }
        createMany: {
          args: Prisma.BookingCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BookingCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>[]
        }
        delete: {
          args: Prisma.BookingDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>
        }
        update: {
          args: Prisma.BookingUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>
        }
        deleteMany: {
          args: Prisma.BookingDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BookingUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BookingUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>[]
        }
        upsert: {
          args: Prisma.BookingUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BookingPayload>
        }
        aggregate: {
          args: Prisma.BookingAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBooking>
        }
        groupBy: {
          args: Prisma.BookingGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BookingGroupByOutputType>[]
        }
        count: {
          args: Prisma.BookingCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BookingCountAggregateOutputType> | number
        }
      }
    }
    Membership: {
      payload: Prisma.$MembershipPayload<ExtArgs>
      fields: Prisma.MembershipFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MembershipFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MembershipFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        findFirst: {
          args: Prisma.MembershipFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MembershipFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        findMany: {
          args: Prisma.MembershipFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>[]
        }
        create: {
          args: Prisma.MembershipCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        createMany: {
          args: Prisma.MembershipCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MembershipCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>[]
        }
        delete: {
          args: Prisma.MembershipDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        update: {
          args: Prisma.MembershipUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        deleteMany: {
          args: Prisma.MembershipDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MembershipUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MembershipUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>[]
        }
        upsert: {
          args: Prisma.MembershipUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MembershipPayload>
        }
        aggregate: {
          args: Prisma.MembershipAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMembership>
        }
        groupBy: {
          args: Prisma.MembershipGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MembershipGroupByOutputType>[]
        }
        count: {
          args: Prisma.MembershipCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MembershipCountAggregateOutputType> | number
        }
      }
    }
    Camp: {
      payload: Prisma.$CampPayload<ExtArgs>
      fields: Prisma.CampFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CampFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CampFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>
        }
        findFirst: {
          args: Prisma.CampFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CampFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>
        }
        findMany: {
          args: Prisma.CampFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>[]
        }
        create: {
          args: Prisma.CampCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>
        }
        createMany: {
          args: Prisma.CampCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CampCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>[]
        }
        delete: {
          args: Prisma.CampDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>
        }
        update: {
          args: Prisma.CampUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>
        }
        deleteMany: {
          args: Prisma.CampDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CampUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CampUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>[]
        }
        upsert: {
          args: Prisma.CampUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampPayload>
        }
        aggregate: {
          args: Prisma.CampAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCamp>
        }
        groupBy: {
          args: Prisma.CampGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CampGroupByOutputType>[]
        }
        count: {
          args: Prisma.CampCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CampCountAggregateOutputType> | number
        }
      }
    }
    CampBooking: {
      payload: Prisma.$CampBookingPayload<ExtArgs>
      fields: Prisma.CampBookingFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CampBookingFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CampBookingFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>
        }
        findFirst: {
          args: Prisma.CampBookingFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CampBookingFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>
        }
        findMany: {
          args: Prisma.CampBookingFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>[]
        }
        create: {
          args: Prisma.CampBookingCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>
        }
        createMany: {
          args: Prisma.CampBookingCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CampBookingCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>[]
        }
        delete: {
          args: Prisma.CampBookingDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>
        }
        update: {
          args: Prisma.CampBookingUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>
        }
        deleteMany: {
          args: Prisma.CampBookingDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CampBookingUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CampBookingUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>[]
        }
        upsert: {
          args: Prisma.CampBookingUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CampBookingPayload>
        }
        aggregate: {
          args: Prisma.CampBookingAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCampBooking>
        }
        groupBy: {
          args: Prisma.CampBookingGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CampBookingGroupByOutputType>[]
        }
        count: {
          args: Prisma.CampBookingCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CampBookingCountAggregateOutputType> | number
        }
      }
    }
    SchoolMember: {
      payload: Prisma.$SchoolMemberPayload<ExtArgs>
      fields: Prisma.SchoolMemberFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SchoolMemberFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SchoolMemberFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>
        }
        findFirst: {
          args: Prisma.SchoolMemberFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SchoolMemberFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>
        }
        findMany: {
          args: Prisma.SchoolMemberFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>[]
        }
        create: {
          args: Prisma.SchoolMemberCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>
        }
        createMany: {
          args: Prisma.SchoolMemberCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SchoolMemberCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>[]
        }
        delete: {
          args: Prisma.SchoolMemberDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>
        }
        update: {
          args: Prisma.SchoolMemberUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>
        }
        deleteMany: {
          args: Prisma.SchoolMemberDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SchoolMemberUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SchoolMemberUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>[]
        }
        upsert: {
          args: Prisma.SchoolMemberUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolMemberPayload>
        }
        aggregate: {
          args: Prisma.SchoolMemberAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSchoolMember>
        }
        groupBy: {
          args: Prisma.SchoolMemberGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SchoolMemberGroupByOutputType>[]
        }
        count: {
          args: Prisma.SchoolMemberCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SchoolMemberCountAggregateOutputType> | number
        }
      }
    }
    SchoolClaim: {
      payload: Prisma.$SchoolClaimPayload<ExtArgs>
      fields: Prisma.SchoolClaimFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SchoolClaimFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SchoolClaimFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>
        }
        findFirst: {
          args: Prisma.SchoolClaimFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SchoolClaimFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>
        }
        findMany: {
          args: Prisma.SchoolClaimFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>[]
        }
        create: {
          args: Prisma.SchoolClaimCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>
        }
        createMany: {
          args: Prisma.SchoolClaimCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SchoolClaimCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>[]
        }
        delete: {
          args: Prisma.SchoolClaimDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>
        }
        update: {
          args: Prisma.SchoolClaimUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>
        }
        deleteMany: {
          args: Prisma.SchoolClaimDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SchoolClaimUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SchoolClaimUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>[]
        }
        upsert: {
          args: Prisma.SchoolClaimUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SchoolClaimPayload>
        }
        aggregate: {
          args: Prisma.SchoolClaimAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSchoolClaim>
        }
        groupBy: {
          args: Prisma.SchoolClaimGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SchoolClaimGroupByOutputType>[]
        }
        count: {
          args: Prisma.SchoolClaimCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SchoolClaimCountAggregateOutputType> | number
        }
      }
    }
    Partner: {
      payload: Prisma.$PartnerPayload<ExtArgs>
      fields: Prisma.PartnerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PartnerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PartnerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>
        }
        findFirst: {
          args: Prisma.PartnerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PartnerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>
        }
        findMany: {
          args: Prisma.PartnerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>[]
        }
        create: {
          args: Prisma.PartnerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>
        }
        createMany: {
          args: Prisma.PartnerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PartnerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>[]
        }
        delete: {
          args: Prisma.PartnerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>
        }
        update: {
          args: Prisma.PartnerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>
        }
        deleteMany: {
          args: Prisma.PartnerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PartnerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PartnerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>[]
        }
        upsert: {
          args: Prisma.PartnerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PartnerPayload>
        }
        aggregate: {
          args: Prisma.PartnerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePartner>
        }
        groupBy: {
          args: Prisma.PartnerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PartnerGroupByOutputType>[]
        }
        count: {
          args: Prisma.PartnerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PartnerCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  phone: 'phone',
  avatarUrl: 'avatarUrl',
  supabaseAuthId: 'supabaseAuthId',
  role: 'role',
  schoolId: 'schoolId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const DisciplineScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug'
} as const

export type DisciplineScalarFieldEnum = (typeof DisciplineScalarFieldEnum)[keyof typeof DisciplineScalarFieldEnum]


export const SchoolDisciplineScalarFieldEnum = {
  schoolId: 'schoolId',
  disciplineId: 'disciplineId'
} as const

export type SchoolDisciplineScalarFieldEnum = (typeof SchoolDisciplineScalarFieldEnum)[keyof typeof SchoolDisciplineScalarFieldEnum]


export const SchoolScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  status: 'status',
  source: 'source',
  country: 'country',
  city: 'city',
  address: 'address',
  postcode: 'postcode',
  lat: 'lat',
  lng: 'lng',
  phone: 'phone',
  email: 'email',
  website: 'website',
  instagram: 'instagram',
  facebook: 'facebook',
  youtube: 'youtube',
  tiktok: 'tiktok',
  description: 'description',
  tagline: 'tagline',
  logoUrl: 'logoUrl',
  coverUrl: 'coverUrl',
  photos: 'photos',
  priceFrom: 'priceFrom',
  hasFreeTrialCls: 'hasFreeTrialCls',
  facilities: 'facilities',
  foundedYear: 'foundedYear',
  totalStudents: 'totalStudents',
  affiliationName: 'affiliationName',
  affiliationUrl: 'affiliationUrl',
  googleRating: 'googleRating',
  googleReviews: 'googleReviews',
  googlePlaceId: 'googlePlaceId',
  stripeAccountId: 'stripeAccountId',
  claimedById: 'claimedById',
  claimedAt: 'claimedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SchoolScalarFieldEnum = (typeof SchoolScalarFieldEnum)[keyof typeof SchoolScalarFieldEnum]


export const InstructorScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  name: 'name',
  role: 'role',
  belt: 'belt',
  bio: 'bio',
  photoUrl: 'photoUrl',
  instagram: 'instagram',
  isHead: 'isHead',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type InstructorScalarFieldEnum = (typeof InstructorScalarFieldEnum)[keyof typeof InstructorScalarFieldEnum]


export const MembershipPlanScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  description: 'description',
  price: 'price',
  currency: 'currency',
  billingCycle: 'billingCycle',
  features: 'features',
  isPopular: 'isPopular',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  stripePriceId: 'stripePriceId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MembershipPlanScalarFieldEnum = (typeof MembershipPlanScalarFieldEnum)[keyof typeof MembershipPlanScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  rating: 'rating',
  title: 'title',
  text: 'text',
  isVerified: 'isVerified',
  isPublished: 'isPublished',
  reply: 'reply',
  repliedAt: 'repliedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const ClassScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  description: 'description',
  disciplineId: 'disciplineId',
  level: 'level',
  duration: 'duration',
  capacity: 'capacity',
  price: 'price',
  currency: 'currency',
  isTrial: 'isTrial',
  isActive: 'isActive',
  schedule: 'schedule',
  instructorId: 'instructorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClassScalarFieldEnum = (typeof ClassScalarFieldEnum)[keyof typeof ClassScalarFieldEnum]


export const BookingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  classId: 'classId',
  scheduledAt: 'scheduledAt',
  status: 'status',
  paymentMethod: 'paymentMethod',
  amountPaid: 'amountPaid',
  currency: 'currency',
  stripePaymentId: 'stripePaymentId',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BookingScalarFieldEnum = (typeof BookingScalarFieldEnum)[keyof typeof BookingScalarFieldEnum]


export const MembershipScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  schoolId: 'schoolId',
  planName: 'planName',
  price: 'price',
  currency: 'currency',
  paymentMethod: 'paymentMethod',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  stripeSubId: 'stripeSubId',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MembershipScalarFieldEnum = (typeof MembershipScalarFieldEnum)[keyof typeof MembershipScalarFieldEnum]


export const CampScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  description: 'description',
  location: 'location',
  country: 'country',
  startDate: 'startDate',
  endDate: 'endDate',
  capacity: 'capacity',
  price: 'price',
  currency: 'currency',
  coverUrl: 'coverUrl',
  isPublished: 'isPublished',
  instructors: 'instructors',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CampScalarFieldEnum = (typeof CampScalarFieldEnum)[keyof typeof CampScalarFieldEnum]


export const CampBookingScalarFieldEnum = {
  id: 'id',
  campId: 'campId',
  userId: 'userId',
  status: 'status',
  amountPaid: 'amountPaid',
  currency: 'currency',
  stripePaymentId: 'stripePaymentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CampBookingScalarFieldEnum = (typeof CampBookingScalarFieldEnum)[keyof typeof CampBookingScalarFieldEnum]


export const SchoolMemberScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  role: 'role',
  status: 'status',
  joinedAt: 'joinedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SchoolMemberScalarFieldEnum = (typeof SchoolMemberScalarFieldEnum)[keyof typeof SchoolMemberScalarFieldEnum]


export const SchoolClaimScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  status: 'status',
  evidence: 'evidence',
  notes: 'notes',
  reviewedBy: 'reviewedBy',
  reviewedAt: 'reviewedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SchoolClaimScalarFieldEnum = (typeof SchoolClaimScalarFieldEnum)[keyof typeof SchoolClaimScalarFieldEnum]


export const PartnerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  title: 'title',
  bio: 'bio',
  photoUrl: 'photoUrl',
  instagram: 'instagram',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PartnerScalarFieldEnum = (typeof PartnerScalarFieldEnum)[keyof typeof PartnerScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'Role[]'
 */
export type ListEnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'SchoolStatus'
 */
export type EnumSchoolStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SchoolStatus'>
    


/**
 * Reference to a field of type 'SchoolStatus[]'
 */
export type ListEnumSchoolStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SchoolStatus[]'>
    


/**
 * Reference to a field of type 'SchoolSource'
 */
export type EnumSchoolSourceFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SchoolSource'>
    


/**
 * Reference to a field of type 'SchoolSource[]'
 */
export type ListEnumSchoolSourceFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SchoolSource[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'BookingStatus'
 */
export type EnumBookingStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BookingStatus'>
    


/**
 * Reference to a field of type 'BookingStatus[]'
 */
export type ListEnumBookingStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BookingStatus[]'>
    


/**
 * Reference to a field of type 'PaymentMethod'
 */
export type EnumPaymentMethodFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PaymentMethod'>
    


/**
 * Reference to a field of type 'PaymentMethod[]'
 */
export type ListEnumPaymentMethodFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PaymentMethod[]'>
    


/**
 * Reference to a field of type 'MembershipStatus'
 */
export type EnumMembershipStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MembershipStatus'>
    


/**
 * Reference to a field of type 'MembershipStatus[]'
 */
export type ListEnumMembershipStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MembershipStatus[]'>
    


/**
 * Reference to a field of type 'SchoolMemberRole'
 */
export type EnumSchoolMemberRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SchoolMemberRole'>
    


/**
 * Reference to a field of type 'SchoolMemberRole[]'
 */
export type ListEnumSchoolMemberRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SchoolMemberRole[]'>
    


/**
 * Reference to a field of type 'SchoolMemberStatus'
 */
export type EnumSchoolMemberStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SchoolMemberStatus'>
    


/**
 * Reference to a field of type 'SchoolMemberStatus[]'
 */
export type ListEnumSchoolMemberStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SchoolMemberStatus[]'>
    


/**
 * Reference to a field of type 'ClaimStatus'
 */
export type EnumClaimStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ClaimStatus'>
    


/**
 * Reference to a field of type 'ClaimStatus[]'
 */
export type ListEnumClaimStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ClaimStatus[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  discipline?: Prisma.DisciplineOmit
  schoolDiscipline?: Prisma.SchoolDisciplineOmit
  school?: Prisma.SchoolOmit
  instructor?: Prisma.InstructorOmit
  membershipPlan?: Prisma.MembershipPlanOmit
  review?: Prisma.ReviewOmit
  class?: Prisma.ClassOmit
  booking?: Prisma.BookingOmit
  membership?: Prisma.MembershipOmit
  camp?: Prisma.CampOmit
  campBooking?: Prisma.CampBookingOmit
  schoolMember?: Prisma.SchoolMemberOmit
  schoolClaim?: Prisma.SchoolClaimOmit
  partner?: Prisma.PartnerOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

