
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Affiliation: 'Affiliation',
  ContentPlatform: 'ContentPlatform',
  ContentSeries: 'ContentSeries',
  ContentVideo: 'ContentVideo',
  ContentAccess: 'ContentAccess',
  User: 'User',
  Discipline: 'Discipline',
  SchoolDiscipline: 'SchoolDiscipline',
  Facility: 'Facility',
  SchoolFacility: 'SchoolFacility',
  School: 'School',
  Instructor: 'Instructor',
  MembershipPlan: 'MembershipPlan',
  Review: 'Review',
  Class: 'Class',
  Event: 'Event',
  EventTicket: 'EventTicket',
  EventBooking: 'EventBooking',
  Booking: 'Booking',
  Membership: 'Membership',
  Camp: 'Camp',
  CampBooking: 'CampBooking',
  SchoolMember: 'SchoolMember',
  SchoolClaim: 'SchoolClaim',
  GradingSystem: 'GradingSystem',
  BeltRank: 'BeltRank',
  Grading: 'Grading',
  Lead: 'Lead',
  LeadNote: 'LeadNote',
  SchoolInvitation: 'SchoolInvitation',
  Waiver: 'Waiver',
  UserWaiver: 'UserWaiver',
  LoginHistory: 'LoginHistory',
  Transaction: 'Transaction',
  UserPreference: 'UserPreference',
  ProductCategory: 'ProductCategory',
  Product: 'Product',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Partner: 'Partner',
  Notification: 'Notification',
  PlatformSettings: 'PlatformSettings',
  SchoolSubscription: 'SchoolSubscription',
  StripeWebhookEvent: 'StripeWebhookEvent'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AffiliationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  logoUrl: 'logoUrl',
  website: 'website',
  instagram: 'instagram',
  country: 'country',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AffiliationScalarFieldEnum = (typeof AffiliationScalarFieldEnum)[keyof typeof AffiliationScalarFieldEnum]


export const ContentPlatformScalarFieldEnum = {
  id: 'id',
  affiliationId: 'affiliationId',
  name: 'name',
  slug: 'slug',
  description: 'description',
  logoUrl: 'logoUrl',
  bannerUrl: 'bannerUrl',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContentPlatformScalarFieldEnum = (typeof ContentPlatformScalarFieldEnum)[keyof typeof ContentPlatformScalarFieldEnum]


export const ContentSeriesScalarFieldEnum = {
  id: 'id',
  platformId: 'platformId',
  title: 'title',
  description: 'description',
  level: 'level',
  thumbnailUrl: 'thumbnailUrl',
  sortOrder: 'sortOrder',
  isPublished: 'isPublished',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContentSeriesScalarFieldEnum = (typeof ContentSeriesScalarFieldEnum)[keyof typeof ContentSeriesScalarFieldEnum]


export const ContentVideoScalarFieldEnum = {
  id: 'id',
  seriesId: 'seriesId',
  title: 'title',
  description: 'description',
  durationMin: 'durationMin',
  videoUrl: 'videoUrl',
  thumbnailUrl: 'thumbnailUrl',
  sortOrder: 'sortOrder',
  isPublished: 'isPublished',
  isFreePreview: 'isFreePreview',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContentVideoScalarFieldEnum = (typeof ContentVideoScalarFieldEnum)[keyof typeof ContentVideoScalarFieldEnum]


export const ContentAccessScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  platformId: 'platformId',
  membershipId: 'membershipId',
  startDate: 'startDate',
  endDate: 'endDate',
  isActive: 'isActive',
  revokedAt: 'revokedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContentAccessScalarFieldEnum = (typeof ContentAccessScalarFieldEnum)[keyof typeof ContentAccessScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  phone: 'phone',
  dateOfBirth: 'dateOfBirth',
  avatarUrl: 'avatarUrl',
  supabaseAuthId: 'supabaseAuthId',
  role: 'role',
  schoolId: 'schoolId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const DisciplineScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug'
} as const

export type DisciplineScalarFieldEnum = (typeof DisciplineScalarFieldEnum)[keyof typeof DisciplineScalarFieldEnum]


export const SchoolDisciplineScalarFieldEnum = {
  schoolId: 'schoolId',
  disciplineId: 'disciplineId'
} as const

export type SchoolDisciplineScalarFieldEnum = (typeof SchoolDisciplineScalarFieldEnum)[keyof typeof SchoolDisciplineScalarFieldEnum]


export const FacilityScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  icon: 'icon'
} as const

export type FacilityScalarFieldEnum = (typeof FacilityScalarFieldEnum)[keyof typeof FacilityScalarFieldEnum]


export const SchoolFacilityScalarFieldEnum = {
  schoolId: 'schoolId',
  facilityId: 'facilityId'
} as const

export type SchoolFacilityScalarFieldEnum = (typeof SchoolFacilityScalarFieldEnum)[keyof typeof SchoolFacilityScalarFieldEnum]


export const SchoolScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  status: 'status',
  source: 'source',
  type: 'type',
  affiliationId: 'affiliationId',
  country: 'country',
  city: 'city',
  address: 'address',
  postcode: 'postcode',
  lat: 'lat',
  lng: 'lng',
  phone: 'phone',
  email: 'email',
  website: 'website',
  language: 'language',
  instagram: 'instagram',
  facebook: 'facebook',
  youtube: 'youtube',
  tiktok: 'tiktok',
  description: 'description',
  tagline: 'tagline',
  logoUrl: 'logoUrl',
  coverUrl: 'coverUrl',
  photos: 'photos',
  priceFrom: 'priceFrom',
  hasFreeTrialCls: 'hasFreeTrialCls',
  facilities: 'facilities',
  foundedYear: 'foundedYear',
  totalStudents: 'totalStudents',
  googleRating: 'googleRating',
  googleReviews: 'googleReviews',
  googlePlaceId: 'googlePlaceId',
  v1UserId: 'v1UserId',
  defaultBookingSettings: 'defaultBookingSettings',
  cancelPolicy: 'cancelPolicy',
  modules: 'modules',
  stripePublishableKey: 'stripePublishableKey',
  stripeSecretKey: 'stripeSecretKey',
  stripeWebhookSecret: 'stripeWebhookSecret',
  revolutPublicKey: 'revolutPublicKey',
  revolutSecretKey: 'revolutSecretKey',
  parentId: 'parentId',
  parentRelationshipType: 'parentRelationshipType',
  leadStage: 'leadStage',
  claimedById: 'claimedById',
  claimedAt: 'claimedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SchoolScalarFieldEnum = (typeof SchoolScalarFieldEnum)[keyof typeof SchoolScalarFieldEnum]


export const InstructorScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  name: 'name',
  role: 'role',
  belt: 'belt',
  bio: 'bio',
  photoUrl: 'photoUrl',
  instagram: 'instagram',
  isHead: 'isHead',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type InstructorScalarFieldEnum = (typeof InstructorScalarFieldEnum)[keyof typeof InstructorScalarFieldEnum]


export const MembershipPlanScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  description: 'description',
  price: 'price',
  currency: 'currency',
  planType: 'planType',
  billingCycle: 'billingCycle',
  validityDays: 'validityDays',
  isPublic: 'isPublic',
  isPopular: 'isPopular',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  classAccess: 'classAccess',
  contentPlatformId: 'contentPlatformId',
  imageUrl: 'imageUrl',
  paymentMethods: 'paymentMethods',
  stripePriceId: 'stripePriceId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MembershipPlanScalarFieldEnum = (typeof MembershipPlanScalarFieldEnum)[keyof typeof MembershipPlanScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  rating: 'rating',
  title: 'title',
  text: 'text',
  isVerified: 'isVerified',
  isPublished: 'isPublished',
  reply: 'reply',
  repliedAt: 'repliedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const ClassScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  description: 'description',
  coverUrl: 'coverUrl',
  disciplineId: 'disciplineId',
  level: 'level',
  duration: 'duration',
  capacity: 'capacity',
  price: 'price',
  currency: 'currency',
  isTrial: 'isTrial',
  isActive: 'isActive',
  isPublished: 'isPublished',
  paymentMethods: 'paymentMethods',
  bookingSettings: 'bookingSettings',
  schedule: 'schedule',
  instructorId: 'instructorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClassScalarFieldEnum = (typeof ClassScalarFieldEnum)[keyof typeof ClassScalarFieldEnum]


export const EventScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  title: 'title',
  description: 'description',
  type: 'type',
  location: 'location',
  startAt: 'startAt',
  endAt: 'endAt',
  capacity: 'capacity',
  coverUrl: 'coverUrl',
  isPublished: 'isPublished',
  isCancelled: 'isCancelled',
  externalUrl: 'externalUrl',
  paymentMethods: 'paymentMethods',
  instructorId: 'instructorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EventScalarFieldEnum = (typeof EventScalarFieldEnum)[keyof typeof EventScalarFieldEnum]


export const EventTicketScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  name: 'name',
  description: 'description',
  price: 'price',
  currency: 'currency',
  capacity: 'capacity',
  sortOrder: 'sortOrder',
  stripePriceId: 'stripePriceId',
  createdAt: 'createdAt'
} as const

export type EventTicketScalarFieldEnum = (typeof EventTicketScalarFieldEnum)[keyof typeof EventTicketScalarFieldEnum]


export const EventBookingScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  ticketId: 'ticketId',
  userId: 'userId',
  ticketName: 'ticketName',
  quantity: 'quantity',
  status: 'status',
  amountPaid: 'amountPaid',
  currency: 'currency',
  paymentMethod: 'paymentMethod',
  stripePaymentId: 'stripePaymentId',
  revolutOrderId: 'revolutOrderId',
  qrToken: 'qrToken',
  checkedIn: 'checkedIn',
  checkedInAt: 'checkedInAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EventBookingScalarFieldEnum = (typeof EventBookingScalarFieldEnum)[keyof typeof EventBookingScalarFieldEnum]


export const BookingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  classId: 'classId',
  membershipId: 'membershipId',
  scheduledAt: 'scheduledAt',
  attendedAt: 'attendedAt',
  status: 'status',
  paymentMethod: 'paymentMethod',
  amountPaid: 'amountPaid',
  currency: 'currency',
  stripePaymentId: 'stripePaymentId',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BookingScalarFieldEnum = (typeof BookingScalarFieldEnum)[keyof typeof BookingScalarFieldEnum]


export const MembershipScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  schoolId: 'schoolId',
  planId: 'planId',
  planName: 'planName',
  price: 'price',
  currency: 'currency',
  paymentMethod: 'paymentMethod',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  classesUsed: 'classesUsed',
  stripeSubId: 'stripeSubId',
  stripeCustomerId: 'stripeCustomerId',
  stripeInvoiceId: 'stripeInvoiceId',
  revolutOrderId: 'revolutOrderId',
  notes: 'notes',
  renewedFromId: 'renewedFromId',
  cancelledAt: 'cancelledAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MembershipScalarFieldEnum = (typeof MembershipScalarFieldEnum)[keyof typeof MembershipScalarFieldEnum]


export const CampScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  description: 'description',
  location: 'location',
  country: 'country',
  startDate: 'startDate',
  endDate: 'endDate',
  capacity: 'capacity',
  price: 'price',
  currency: 'currency',
  coverUrl: 'coverUrl',
  isPublished: 'isPublished',
  instructors: 'instructors',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CampScalarFieldEnum = (typeof CampScalarFieldEnum)[keyof typeof CampScalarFieldEnum]


export const CampBookingScalarFieldEnum = {
  id: 'id',
  campId: 'campId',
  userId: 'userId',
  status: 'status',
  amountPaid: 'amountPaid',
  currency: 'currency',
  stripePaymentId: 'stripePaymentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CampBookingScalarFieldEnum = (typeof CampBookingScalarFieldEnum)[keyof typeof CampBookingScalarFieldEnum]


export const SchoolMemberScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  role: 'role',
  status: 'status',
  joinedAt: 'joinedAt',
  belt: 'belt',
  beltRankId: 'beltRankId',
  beltDegree: 'beltDegree',
  beltDate: 'beltDate',
  emergencyContact: 'emergencyContact',
  medicalNotes: 'medicalNotes',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SchoolMemberScalarFieldEnum = (typeof SchoolMemberScalarFieldEnum)[keyof typeof SchoolMemberScalarFieldEnum]


export const SchoolClaimScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  status: 'status',
  evidence: 'evidence',
  notes: 'notes',
  reviewedBy: 'reviewedBy',
  reviewedAt: 'reviewedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SchoolClaimScalarFieldEnum = (typeof SchoolClaimScalarFieldEnum)[keyof typeof SchoolClaimScalarFieldEnum]


export const GradingSystemScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  activity: 'activity',
  isDefault: 'isDefault',
  isActive: 'isActive',
  requireApproval: 'requireApproval',
  gradingFee: 'gradingFee',
  notifyStudent: 'notifyStudent',
  notifyInstructor: 'notifyInstructor',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GradingSystemScalarFieldEnum = (typeof GradingSystemScalarFieldEnum)[keyof typeof GradingSystemScalarFieldEnum]


export const BeltRankScalarFieldEnum = {
  id: 'id',
  systemId: 'systemId',
  order: 'order',
  name: 'name',
  color: 'color',
  maxDegrees: 'maxDegrees',
  minAge: 'minAge',
  minMonthsAtPrevious: 'minMonthsAtPrevious',
  totalClassesRequired: 'totalClassesRequired',
  classesPerPeriod: 'classesPerPeriod',
  periodType: 'periodType',
  classTypeIds: 'classTypeIds',
  requireCompetition: 'requireCompetition',
  requireExam: 'requireExam',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BeltRankScalarFieldEnum = (typeof BeltRankScalarFieldEnum)[keyof typeof BeltRankScalarFieldEnum]


export const GradingScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  promotedById: 'promotedById',
  fromBelt: 'fromBelt',
  fromBeltRankId: 'fromBeltRankId',
  toBelt: 'toBelt',
  toBeltRankId: 'toBeltRankId',
  toDegree: 'toDegree',
  gradedAt: 'gradedAt',
  notes: 'notes',
  isPublic: 'isPublic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GradingScalarFieldEnum = (typeof GradingScalarFieldEnum)[keyof typeof GradingScalarFieldEnum]


export const LeadScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  email: 'email',
  phone: 'phone',
  source: 'source',
  status: 'status',
  message: 'message',
  interestedIn: 'interestedIn',
  convertedUserId: 'convertedUserId',
  convertedAt: 'convertedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LeadScalarFieldEnum = (typeof LeadScalarFieldEnum)[keyof typeof LeadScalarFieldEnum]


export const LeadNoteScalarFieldEnum = {
  id: 'id',
  leadId: 'leadId',
  authorId: 'authorId',
  text: 'text',
  createdAt: 'createdAt'
} as const

export type LeadNoteScalarFieldEnum = (typeof LeadNoteScalarFieldEnum)[keyof typeof LeadNoteScalarFieldEnum]


export const SchoolInvitationScalarFieldEnum = {
  id: 'id',
  token: 'token',
  name: 'name',
  email: 'email',
  phone: 'phone',
  city: 'city',
  country: 'country',
  activities: 'activities',
  website: 'website',
  notes: 'notes',
  status: 'status',
  source: 'source',
  invitedById: 'invitedById',
  schoolId: 'schoolId',
  isActive: 'isActive',
  sentAt: 'sentAt',
  openedAt: 'openedAt',
  registeredAt: 'registeredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SchoolInvitationScalarFieldEnum = (typeof SchoolInvitationScalarFieldEnum)[keyof typeof SchoolInvitationScalarFieldEnum]


export const WaiverScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  title: 'title',
  content: 'content',
  version: 'version',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WaiverScalarFieldEnum = (typeof WaiverScalarFieldEnum)[keyof typeof WaiverScalarFieldEnum]


export const UserWaiverScalarFieldEnum = {
  id: 'id',
  waiverId: 'waiverId',
  userId: 'userId',
  signedAt: 'signedAt',
  ipAddress: 'ipAddress',
  signature: 'signature'
} as const

export type UserWaiverScalarFieldEnum = (typeof UserWaiverScalarFieldEnum)[keyof typeof UserWaiverScalarFieldEnum]


export const LoginHistoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  userEmail: 'userEmail',
  userName: 'userName',
  userRole: 'userRole',
  ipAddress: 'ipAddress',
  country: 'country',
  city: 'city',
  userAgent: 'userAgent',
  browser: 'browser',
  os: 'os',
  device: 'device',
  createdAt: 'createdAt'
} as const

export type LoginHistoryScalarFieldEnum = (typeof LoginHistoryScalarFieldEnum)[keyof typeof LoginHistoryScalarFieldEnum]


export const TransactionScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  type: 'type',
  status: 'status',
  category: 'category',
  paymentMethod: 'paymentMethod',
  amount: 'amount',
  currency: 'currency',
  description: 'description',
  date: 'date',
  membershipId: 'membershipId',
  bookingId: 'bookingId',
  userId: 'userId',
  stripePaymentIntentId: 'stripePaymentIntentId',
  notes: 'notes',
  periodStart: 'periodStart',
  periodEnd: 'periodEnd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TransactionScalarFieldEnum = (typeof TransactionScalarFieldEnum)[keyof typeof TransactionScalarFieldEnum]


export const UserPreferenceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  lastSchoolId: 'lastSchoolId',
  lastContextType: 'lastContextType',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserPreferenceScalarFieldEnum = (typeof UserPreferenceScalarFieldEnum)[keyof typeof UserPreferenceScalarFieldEnum]


export const ProductCategoryScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  name: 'name',
  slug: 'slug'
} as const

export type ProductCategoryScalarFieldEnum = (typeof ProductCategoryScalarFieldEnum)[keyof typeof ProductCategoryScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  categoryId: 'categoryId',
  name: 'name',
  description: 'description',
  price: 'price',
  currency: 'currency',
  stock: 'stock',
  imageUrl: 'imageUrl',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  userId: 'userId',
  status: 'status',
  total: 'total',
  currency: 'currency',
  stripePaymentIntentId: 'stripePaymentIntentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  currency: 'currency'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const PartnerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  title: 'title',
  bio: 'bio',
  photoUrl: 'photoUrl',
  instagram: 'instagram',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PartnerScalarFieldEnum = (typeof PartnerScalarFieldEnum)[keyof typeof PartnerScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  type: 'type',
  title: 'title',
  body: 'body',
  href: 'href',
  read: 'read',
  createdAt: 'createdAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const PlatformSettingsScalarFieldEnum = {
  id: 'id',
  enabledPaymentMethods: 'enabledPaymentMethods',
  defaultCurrency: 'defaultCurrency',
  defaultTaxName: 'defaultTaxName',
  defaultTaxRate: 'defaultTaxRate',
  defaultTaxNumber: 'defaultTaxNumber',
  taxActive: 'taxActive',
  gracePeriodDays: 'gracePeriodDays',
  planCurrency: 'planCurrency',
  planPriceMonthly: 'planPriceMonthly',
  planPriceQuarterly: 'planPriceQuarterly',
  planPriceAnnual: 'planPriceAnnual',
  stripePriceIdMonthly: 'stripePriceIdMonthly',
  stripePriceIdQuarterly: 'stripePriceIdQuarterly',
  stripePriceIdAnnual: 'stripePriceIdAnnual',
  notifyNewSchool: 'notifyNewSchool',
  notifyVerificationReq: 'notifyVerificationReq',
  notifyWeeklyReport: 'notifyWeeklyReport',
  allowSelfRegistration: 'allowSelfRegistration',
  requireEmailVerification: 'requireEmailVerification',
  maintenanceMode: 'maintenanceMode',
  superAdminEmail: 'superAdminEmail',
  supportEmail: 'supportEmail',
  emailSenderName: 'emailSenderName',
  updatedAt: 'updatedAt'
} as const

export type PlatformSettingsScalarFieldEnum = (typeof PlatformSettingsScalarFieldEnum)[keyof typeof PlatformSettingsScalarFieldEnum]


export const SchoolSubscriptionScalarFieldEnum = {
  id: 'id',
  schoolId: 'schoolId',
  billingCycle: 'billingCycle',
  status: 'status',
  stripeCustomerId: 'stripeCustomerId',
  stripeSubscriptionId: 'stripeSubscriptionId',
  currentPeriodEnd: 'currentPeriodEnd',
  trialEndsAt: 'trialEndsAt',
  cancelledAt: 'cancelledAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SchoolSubscriptionScalarFieldEnum = (typeof SchoolSubscriptionScalarFieldEnum)[keyof typeof SchoolSubscriptionScalarFieldEnum]


export const StripeWebhookEventScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  type: 'type',
  status: 'status',
  processedAt: 'processedAt',
  error: 'error',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StripeWebhookEventScalarFieldEnum = (typeof StripeWebhookEventScalarFieldEnum)[keyof typeof StripeWebhookEventScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

