
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Affiliation
 * 
 */
export type Affiliation = Prisma.AffiliationModel
/**
 * Model ContentPlatform
 * 
 */
export type ContentPlatform = Prisma.ContentPlatformModel
/**
 * Model ContentSeries
 * 
 */
export type ContentSeries = Prisma.ContentSeriesModel
/**
 * Model ContentVideo
 * 
 */
export type ContentVideo = Prisma.ContentVideoModel
/**
 * Model ContentAccess
 * 
 */
export type ContentAccess = Prisma.ContentAccessModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Discipline
 * 
 */
export type Discipline = Prisma.DisciplineModel
/**
 * Model SchoolDiscipline
 * 
 */
export type SchoolDiscipline = Prisma.SchoolDisciplineModel
/**
 * Model School
 * 
 */
export type School = Prisma.SchoolModel
/**
 * Model Instructor
 * 
 */
export type Instructor = Prisma.InstructorModel
/**
 * Model MembershipPlan
 * 
 */
export type MembershipPlan = Prisma.MembershipPlanModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model Class
 * 
 */
export type Class = Prisma.ClassModel
/**
 * Model Event
 * 
 */
export type Event = Prisma.EventModel
/**
 * Model EventTicket
 * 
 */
export type EventTicket = Prisma.EventTicketModel
/**
 * Model Booking
 * 
 */
export type Booking = Prisma.BookingModel
/**
 * Model Membership
 * 
 */
export type Membership = Prisma.MembershipModel
/**
 * Model Camp
 * 
 */
export type Camp = Prisma.CampModel
/**
 * Model CampBooking
 * 
 */
export type CampBooking = Prisma.CampBookingModel
/**
 * Model SchoolMember
 * 
 */
export type SchoolMember = Prisma.SchoolMemberModel
/**
 * Model SchoolClaim
 * 
 */
export type SchoolClaim = Prisma.SchoolClaimModel
/**
 * Model GradingSystem
 * 
 */
export type GradingSystem = Prisma.GradingSystemModel
/**
 * Model BeltRank
 * 
 */
export type BeltRank = Prisma.BeltRankModel
/**
 * Model Grading
 * 
 */
export type Grading = Prisma.GradingModel
/**
 * Model Lead
 * 
 */
export type Lead = Prisma.LeadModel
/**
 * Model LeadNote
 * 
 */
export type LeadNote = Prisma.LeadNoteModel
/**
 * Model SchoolInvitation
 * 
 */
export type SchoolInvitation = Prisma.SchoolInvitationModel
/**
 * Model Waiver
 * 
 */
export type Waiver = Prisma.WaiverModel
/**
 * Model UserWaiver
 * 
 */
export type UserWaiver = Prisma.UserWaiverModel
/**
 * Model Transaction
 * 
 */
export type Transaction = Prisma.TransactionModel
/**
 * Model UserPreference
 * 
 */
export type UserPreference = Prisma.UserPreferenceModel
/**
 * Model ProductCategory
 * 
 */
export type ProductCategory = Prisma.ProductCategoryModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model Partner
 * 
 */
export type Partner = Prisma.PartnerModel
