
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CampBooking` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CampBooking
 * 
 */
export type CampBookingModel = runtime.Types.Result.DefaultSelection<Prisma.$CampBookingPayload>

export type AggregateCampBooking = {
  _count: CampBookingCountAggregateOutputType | null
  _avg: CampBookingAvgAggregateOutputType | null
  _sum: CampBookingSumAggregateOutputType | null
  _min: CampBookingMinAggregateOutputType | null
  _max: CampBookingMaxAggregateOutputType | null
}

export type CampBookingAvgAggregateOutputType = {
  amountPaid: number | null
}

export type CampBookingSumAggregateOutputType = {
  amountPaid: number | null
}

export type CampBookingMinAggregateOutputType = {
  id: string | null
  campId: string | null
  userId: string | null
  status: $Enums.BookingStatus | null
  amountPaid: number | null
  currency: string | null
  stripePaymentId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CampBookingMaxAggregateOutputType = {
  id: string | null
  campId: string | null
  userId: string | null
  status: $Enums.BookingStatus | null
  amountPaid: number | null
  currency: string | null
  stripePaymentId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CampBookingCountAggregateOutputType = {
  id: number
  campId: number
  userId: number
  status: number
  amountPaid: number
  currency: number
  stripePaymentId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CampBookingAvgAggregateInputType = {
  amountPaid?: true
}

export type CampBookingSumAggregateInputType = {
  amountPaid?: true
}

export type CampBookingMinAggregateInputType = {
  id?: true
  campId?: true
  userId?: true
  status?: true
  amountPaid?: true
  currency?: true
  stripePaymentId?: true
  createdAt?: true
  updatedAt?: true
}

export type CampBookingMaxAggregateInputType = {
  id?: true
  campId?: true
  userId?: true
  status?: true
  amountPaid?: true
  currency?: true
  stripePaymentId?: true
  createdAt?: true
  updatedAt?: true
}

export type CampBookingCountAggregateInputType = {
  id?: true
  campId?: true
  userId?: true
  status?: true
  amountPaid?: true
  currency?: true
  stripePaymentId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CampBookingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CampBooking to aggregate.
   */
  where?: Prisma.CampBookingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CampBookings to fetch.
   */
  orderBy?: Prisma.CampBookingOrderByWithRelationInput | Prisma.CampBookingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CampBookingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CampBookings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CampBookings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CampBookings
  **/
  _count?: true | CampBookingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CampBookingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CampBookingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CampBookingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CampBookingMaxAggregateInputType
}

export type GetCampBookingAggregateType<T extends CampBookingAggregateArgs> = {
      [P in keyof T & keyof AggregateCampBooking]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCampBooking[P]>
    : Prisma.GetScalarType<T[P], AggregateCampBooking[P]>
}




export type CampBookingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CampBookingWhereInput
  orderBy?: Prisma.CampBookingOrderByWithAggregationInput | Prisma.CampBookingOrderByWithAggregationInput[]
  by: Prisma.CampBookingScalarFieldEnum[] | Prisma.CampBookingScalarFieldEnum
  having?: Prisma.CampBookingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CampBookingCountAggregateInputType | true
  _avg?: CampBookingAvgAggregateInputType
  _sum?: CampBookingSumAggregateInputType
  _min?: CampBookingMinAggregateInputType
  _max?: CampBookingMaxAggregateInputType
}

export type CampBookingGroupByOutputType = {
  id: string
  campId: string
  userId: string
  status: $Enums.BookingStatus
  amountPaid: number | null
  currency: string
  stripePaymentId: string | null
  createdAt: Date
  updatedAt: Date
  _count: CampBookingCountAggregateOutputType | null
  _avg: CampBookingAvgAggregateOutputType | null
  _sum: CampBookingSumAggregateOutputType | null
  _min: CampBookingMinAggregateOutputType | null
  _max: CampBookingMaxAggregateOutputType | null
}

export type GetCampBookingGroupByPayload<T extends CampBookingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CampBookingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CampBookingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CampBookingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CampBookingGroupByOutputType[P]>
      }
    >
  >



export type CampBookingWhereInput = {
  AND?: Prisma.CampBookingWhereInput | Prisma.CampBookingWhereInput[]
  OR?: Prisma.CampBookingWhereInput[]
  NOT?: Prisma.CampBookingWhereInput | Prisma.CampBookingWhereInput[]
  id?: Prisma.StringFilter<"CampBooking"> | string
  campId?: Prisma.StringFilter<"CampBooking"> | string
  userId?: Prisma.StringFilter<"CampBooking"> | string
  status?: Prisma.EnumBookingStatusFilter<"CampBooking"> | $Enums.BookingStatus
  amountPaid?: Prisma.FloatNullableFilter<"CampBooking"> | number | null
  currency?: Prisma.StringFilter<"CampBooking"> | string
  stripePaymentId?: Prisma.StringNullableFilter<"CampBooking"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CampBooking"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CampBooking"> | Date | string
  camp?: Prisma.XOR<Prisma.CampScalarRelationFilter, Prisma.CampWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type CampBookingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  campId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountPaid?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripePaymentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  camp?: Prisma.CampOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type CampBookingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CampBookingWhereInput | Prisma.CampBookingWhereInput[]
  OR?: Prisma.CampBookingWhereInput[]
  NOT?: Prisma.CampBookingWhereInput | Prisma.CampBookingWhereInput[]
  campId?: Prisma.StringFilter<"CampBooking"> | string
  userId?: Prisma.StringFilter<"CampBooking"> | string
  status?: Prisma.EnumBookingStatusFilter<"CampBooking"> | $Enums.BookingStatus
  amountPaid?: Prisma.FloatNullableFilter<"CampBooking"> | number | null
  currency?: Prisma.StringFilter<"CampBooking"> | string
  stripePaymentId?: Prisma.StringNullableFilter<"CampBooking"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CampBooking"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CampBooking"> | Date | string
  camp?: Prisma.XOR<Prisma.CampScalarRelationFilter, Prisma.CampWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type CampBookingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  campId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountPaid?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripePaymentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CampBookingCountOrderByAggregateInput
  _avg?: Prisma.CampBookingAvgOrderByAggregateInput
  _max?: Prisma.CampBookingMaxOrderByAggregateInput
  _min?: Prisma.CampBookingMinOrderByAggregateInput
  _sum?: Prisma.CampBookingSumOrderByAggregateInput
}

export type CampBookingScalarWhereWithAggregatesInput = {
  AND?: Prisma.CampBookingScalarWhereWithAggregatesInput | Prisma.CampBookingScalarWhereWithAggregatesInput[]
  OR?: Prisma.CampBookingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CampBookingScalarWhereWithAggregatesInput | Prisma.CampBookingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CampBooking"> | string
  campId?: Prisma.StringWithAggregatesFilter<"CampBooking"> | string
  userId?: Prisma.StringWithAggregatesFilter<"CampBooking"> | string
  status?: Prisma.EnumBookingStatusWithAggregatesFilter<"CampBooking"> | $Enums.BookingStatus
  amountPaid?: Prisma.FloatNullableWithAggregatesFilter<"CampBooking"> | number | null
  currency?: Prisma.StringWithAggregatesFilter<"CampBooking"> | string
  stripePaymentId?: Prisma.StringNullableWithAggregatesFilter<"CampBooking"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CampBooking"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CampBooking"> | Date | string
}

export type CampBookingCreateInput = {
  id?: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  camp: Prisma.CampCreateNestedOneWithoutBookingsInput
  user: Prisma.UserCreateNestedOneWithoutCampBookingsInput
}

export type CampBookingUncheckedCreateInput = {
  id?: string
  campId: string
  userId: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CampBookingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  camp?: Prisma.CampUpdateOneRequiredWithoutBookingsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutCampBookingsNestedInput
}

export type CampBookingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampBookingCreateManyInput = {
  id?: string
  campId: string
  userId: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CampBookingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampBookingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampBookingListRelationFilter = {
  every?: Prisma.CampBookingWhereInput
  some?: Prisma.CampBookingWhereInput
  none?: Prisma.CampBookingWhereInput
}

export type CampBookingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CampBookingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountPaid?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripePaymentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CampBookingAvgOrderByAggregateInput = {
  amountPaid?: Prisma.SortOrder
}

export type CampBookingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountPaid?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripePaymentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CampBookingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  amountPaid?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  stripePaymentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CampBookingSumOrderByAggregateInput = {
  amountPaid?: Prisma.SortOrder
}

export type CampBookingCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CampBookingCreateWithoutUserInput, Prisma.CampBookingUncheckedCreateWithoutUserInput> | Prisma.CampBookingCreateWithoutUserInput[] | Prisma.CampBookingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CampBookingCreateOrConnectWithoutUserInput | Prisma.CampBookingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CampBookingCreateManyUserInputEnvelope
  connect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
}

export type CampBookingUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CampBookingCreateWithoutUserInput, Prisma.CampBookingUncheckedCreateWithoutUserInput> | Prisma.CampBookingCreateWithoutUserInput[] | Prisma.CampBookingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CampBookingCreateOrConnectWithoutUserInput | Prisma.CampBookingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CampBookingCreateManyUserInputEnvelope
  connect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
}

export type CampBookingUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CampBookingCreateWithoutUserInput, Prisma.CampBookingUncheckedCreateWithoutUserInput> | Prisma.CampBookingCreateWithoutUserInput[] | Prisma.CampBookingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CampBookingCreateOrConnectWithoutUserInput | Prisma.CampBookingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CampBookingUpsertWithWhereUniqueWithoutUserInput | Prisma.CampBookingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CampBookingCreateManyUserInputEnvelope
  set?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  disconnect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  delete?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  connect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  update?: Prisma.CampBookingUpdateWithWhereUniqueWithoutUserInput | Prisma.CampBookingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CampBookingUpdateManyWithWhereWithoutUserInput | Prisma.CampBookingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CampBookingScalarWhereInput | Prisma.CampBookingScalarWhereInput[]
}

export type CampBookingUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CampBookingCreateWithoutUserInput, Prisma.CampBookingUncheckedCreateWithoutUserInput> | Prisma.CampBookingCreateWithoutUserInput[] | Prisma.CampBookingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CampBookingCreateOrConnectWithoutUserInput | Prisma.CampBookingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CampBookingUpsertWithWhereUniqueWithoutUserInput | Prisma.CampBookingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CampBookingCreateManyUserInputEnvelope
  set?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  disconnect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  delete?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  connect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  update?: Prisma.CampBookingUpdateWithWhereUniqueWithoutUserInput | Prisma.CampBookingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CampBookingUpdateManyWithWhereWithoutUserInput | Prisma.CampBookingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CampBookingScalarWhereInput | Prisma.CampBookingScalarWhereInput[]
}

export type CampBookingCreateNestedManyWithoutCampInput = {
  create?: Prisma.XOR<Prisma.CampBookingCreateWithoutCampInput, Prisma.CampBookingUncheckedCreateWithoutCampInput> | Prisma.CampBookingCreateWithoutCampInput[] | Prisma.CampBookingUncheckedCreateWithoutCampInput[]
  connectOrCreate?: Prisma.CampBookingCreateOrConnectWithoutCampInput | Prisma.CampBookingCreateOrConnectWithoutCampInput[]
  createMany?: Prisma.CampBookingCreateManyCampInputEnvelope
  connect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
}

export type CampBookingUncheckedCreateNestedManyWithoutCampInput = {
  create?: Prisma.XOR<Prisma.CampBookingCreateWithoutCampInput, Prisma.CampBookingUncheckedCreateWithoutCampInput> | Prisma.CampBookingCreateWithoutCampInput[] | Prisma.CampBookingUncheckedCreateWithoutCampInput[]
  connectOrCreate?: Prisma.CampBookingCreateOrConnectWithoutCampInput | Prisma.CampBookingCreateOrConnectWithoutCampInput[]
  createMany?: Prisma.CampBookingCreateManyCampInputEnvelope
  connect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
}

export type CampBookingUpdateManyWithoutCampNestedInput = {
  create?: Prisma.XOR<Prisma.CampBookingCreateWithoutCampInput, Prisma.CampBookingUncheckedCreateWithoutCampInput> | Prisma.CampBookingCreateWithoutCampInput[] | Prisma.CampBookingUncheckedCreateWithoutCampInput[]
  connectOrCreate?: Prisma.CampBookingCreateOrConnectWithoutCampInput | Prisma.CampBookingCreateOrConnectWithoutCampInput[]
  upsert?: Prisma.CampBookingUpsertWithWhereUniqueWithoutCampInput | Prisma.CampBookingUpsertWithWhereUniqueWithoutCampInput[]
  createMany?: Prisma.CampBookingCreateManyCampInputEnvelope
  set?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  disconnect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  delete?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  connect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  update?: Prisma.CampBookingUpdateWithWhereUniqueWithoutCampInput | Prisma.CampBookingUpdateWithWhereUniqueWithoutCampInput[]
  updateMany?: Prisma.CampBookingUpdateManyWithWhereWithoutCampInput | Prisma.CampBookingUpdateManyWithWhereWithoutCampInput[]
  deleteMany?: Prisma.CampBookingScalarWhereInput | Prisma.CampBookingScalarWhereInput[]
}

export type CampBookingUncheckedUpdateManyWithoutCampNestedInput = {
  create?: Prisma.XOR<Prisma.CampBookingCreateWithoutCampInput, Prisma.CampBookingUncheckedCreateWithoutCampInput> | Prisma.CampBookingCreateWithoutCampInput[] | Prisma.CampBookingUncheckedCreateWithoutCampInput[]
  connectOrCreate?: Prisma.CampBookingCreateOrConnectWithoutCampInput | Prisma.CampBookingCreateOrConnectWithoutCampInput[]
  upsert?: Prisma.CampBookingUpsertWithWhereUniqueWithoutCampInput | Prisma.CampBookingUpsertWithWhereUniqueWithoutCampInput[]
  createMany?: Prisma.CampBookingCreateManyCampInputEnvelope
  set?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  disconnect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  delete?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  connect?: Prisma.CampBookingWhereUniqueInput | Prisma.CampBookingWhereUniqueInput[]
  update?: Prisma.CampBookingUpdateWithWhereUniqueWithoutCampInput | Prisma.CampBookingUpdateWithWhereUniqueWithoutCampInput[]
  updateMany?: Prisma.CampBookingUpdateManyWithWhereWithoutCampInput | Prisma.CampBookingUpdateManyWithWhereWithoutCampInput[]
  deleteMany?: Prisma.CampBookingScalarWhereInput | Prisma.CampBookingScalarWhereInput[]
}

export type CampBookingCreateWithoutUserInput = {
  id?: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  camp: Prisma.CampCreateNestedOneWithoutBookingsInput
}

export type CampBookingUncheckedCreateWithoutUserInput = {
  id?: string
  campId: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CampBookingCreateOrConnectWithoutUserInput = {
  where: Prisma.CampBookingWhereUniqueInput
  create: Prisma.XOR<Prisma.CampBookingCreateWithoutUserInput, Prisma.CampBookingUncheckedCreateWithoutUserInput>
}

export type CampBookingCreateManyUserInputEnvelope = {
  data: Prisma.CampBookingCreateManyUserInput | Prisma.CampBookingCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type CampBookingUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CampBookingWhereUniqueInput
  update: Prisma.XOR<Prisma.CampBookingUpdateWithoutUserInput, Prisma.CampBookingUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CampBookingCreateWithoutUserInput, Prisma.CampBookingUncheckedCreateWithoutUserInput>
}

export type CampBookingUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CampBookingWhereUniqueInput
  data: Prisma.XOR<Prisma.CampBookingUpdateWithoutUserInput, Prisma.CampBookingUncheckedUpdateWithoutUserInput>
}

export type CampBookingUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CampBookingScalarWhereInput
  data: Prisma.XOR<Prisma.CampBookingUpdateManyMutationInput, Prisma.CampBookingUncheckedUpdateManyWithoutUserInput>
}

export type CampBookingScalarWhereInput = {
  AND?: Prisma.CampBookingScalarWhereInput | Prisma.CampBookingScalarWhereInput[]
  OR?: Prisma.CampBookingScalarWhereInput[]
  NOT?: Prisma.CampBookingScalarWhereInput | Prisma.CampBookingScalarWhereInput[]
  id?: Prisma.StringFilter<"CampBooking"> | string
  campId?: Prisma.StringFilter<"CampBooking"> | string
  userId?: Prisma.StringFilter<"CampBooking"> | string
  status?: Prisma.EnumBookingStatusFilter<"CampBooking"> | $Enums.BookingStatus
  amountPaid?: Prisma.FloatNullableFilter<"CampBooking"> | number | null
  currency?: Prisma.StringFilter<"CampBooking"> | string
  stripePaymentId?: Prisma.StringNullableFilter<"CampBooking"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CampBooking"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CampBooking"> | Date | string
}

export type CampBookingCreateWithoutCampInput = {
  id?: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCampBookingsInput
}

export type CampBookingUncheckedCreateWithoutCampInput = {
  id?: string
  userId: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CampBookingCreateOrConnectWithoutCampInput = {
  where: Prisma.CampBookingWhereUniqueInput
  create: Prisma.XOR<Prisma.CampBookingCreateWithoutCampInput, Prisma.CampBookingUncheckedCreateWithoutCampInput>
}

export type CampBookingCreateManyCampInputEnvelope = {
  data: Prisma.CampBookingCreateManyCampInput | Prisma.CampBookingCreateManyCampInput[]
  skipDuplicates?: boolean
}

export type CampBookingUpsertWithWhereUniqueWithoutCampInput = {
  where: Prisma.CampBookingWhereUniqueInput
  update: Prisma.XOR<Prisma.CampBookingUpdateWithoutCampInput, Prisma.CampBookingUncheckedUpdateWithoutCampInput>
  create: Prisma.XOR<Prisma.CampBookingCreateWithoutCampInput, Prisma.CampBookingUncheckedCreateWithoutCampInput>
}

export type CampBookingUpdateWithWhereUniqueWithoutCampInput = {
  where: Prisma.CampBookingWhereUniqueInput
  data: Prisma.XOR<Prisma.CampBookingUpdateWithoutCampInput, Prisma.CampBookingUncheckedUpdateWithoutCampInput>
}

export type CampBookingUpdateManyWithWhereWithoutCampInput = {
  where: Prisma.CampBookingScalarWhereInput
  data: Prisma.XOR<Prisma.CampBookingUpdateManyMutationInput, Prisma.CampBookingUncheckedUpdateManyWithoutCampInput>
}

export type CampBookingCreateManyUserInput = {
  id?: string
  campId: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CampBookingUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  camp?: Prisma.CampUpdateOneRequiredWithoutBookingsNestedInput
}

export type CampBookingUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampBookingUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampBookingCreateManyCampInput = {
  id?: string
  userId: string
  status?: $Enums.BookingStatus
  amountPaid?: number | null
  currency?: string
  stripePaymentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CampBookingUpdateWithoutCampInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCampBookingsNestedInput
}

export type CampBookingUncheckedUpdateWithoutCampInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CampBookingUncheckedUpdateManyWithoutCampInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBookingStatusFieldUpdateOperationsInput | $Enums.BookingStatus
  amountPaid?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  stripePaymentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CampBookingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campId?: boolean
  userId?: boolean
  status?: boolean
  amountPaid?: boolean
  currency?: boolean
  stripePaymentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  camp?: boolean | Prisma.CampDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["campBooking"]>

export type CampBookingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campId?: boolean
  userId?: boolean
  status?: boolean
  amountPaid?: boolean
  currency?: boolean
  stripePaymentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  camp?: boolean | Prisma.CampDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["campBooking"]>

export type CampBookingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campId?: boolean
  userId?: boolean
  status?: boolean
  amountPaid?: boolean
  currency?: boolean
  stripePaymentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  camp?: boolean | Prisma.CampDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["campBooking"]>

export type CampBookingSelectScalar = {
  id?: boolean
  campId?: boolean
  userId?: boolean
  status?: boolean
  amountPaid?: boolean
  currency?: boolean
  stripePaymentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CampBookingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "campId" | "userId" | "status" | "amountPaid" | "currency" | "stripePaymentId" | "createdAt" | "updatedAt", ExtArgs["result"]["campBooking"]>
export type CampBookingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  camp?: boolean | Prisma.CampDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CampBookingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  camp?: boolean | Prisma.CampDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CampBookingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  camp?: boolean | Prisma.CampDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CampBookingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CampBooking"
  objects: {
    camp: Prisma.$CampPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    campId: string
    userId: string
    status: $Enums.BookingStatus
    amountPaid: number | null
    currency: string
    stripePaymentId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["campBooking"]>
  composites: {}
}

export type CampBookingGetPayload<S extends boolean | null | undefined | CampBookingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CampBookingPayload, S>

export type CampBookingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CampBookingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CampBookingCountAggregateInputType | true
  }

export interface CampBookingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CampBooking'], meta: { name: 'CampBooking' } }
  /**
   * Find zero or one CampBooking that matches the filter.
   * @param {CampBookingFindUniqueArgs} args - Arguments to find a CampBooking
   * @example
   * // Get one CampBooking
   * const campBooking = await prisma.campBooking.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CampBookingFindUniqueArgs>(args: Prisma.SelectSubset<T, CampBookingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CampBookingClient<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CampBooking that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CampBookingFindUniqueOrThrowArgs} args - Arguments to find a CampBooking
   * @example
   * // Get one CampBooking
   * const campBooking = await prisma.campBooking.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CampBookingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CampBookingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CampBookingClient<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CampBooking that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampBookingFindFirstArgs} args - Arguments to find a CampBooking
   * @example
   * // Get one CampBooking
   * const campBooking = await prisma.campBooking.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CampBookingFindFirstArgs>(args?: Prisma.SelectSubset<T, CampBookingFindFirstArgs<ExtArgs>>): Prisma.Prisma__CampBookingClient<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CampBooking that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampBookingFindFirstOrThrowArgs} args - Arguments to find a CampBooking
   * @example
   * // Get one CampBooking
   * const campBooking = await prisma.campBooking.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CampBookingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CampBookingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CampBookingClient<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CampBookings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampBookingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CampBookings
   * const campBookings = await prisma.campBooking.findMany()
   * 
   * // Get first 10 CampBookings
   * const campBookings = await prisma.campBooking.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const campBookingWithIdOnly = await prisma.campBooking.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CampBookingFindManyArgs>(args?: Prisma.SelectSubset<T, CampBookingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CampBooking.
   * @param {CampBookingCreateArgs} args - Arguments to create a CampBooking.
   * @example
   * // Create one CampBooking
   * const CampBooking = await prisma.campBooking.create({
   *   data: {
   *     // ... data to create a CampBooking
   *   }
   * })
   * 
   */
  create<T extends CampBookingCreateArgs>(args: Prisma.SelectSubset<T, CampBookingCreateArgs<ExtArgs>>): Prisma.Prisma__CampBookingClient<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CampBookings.
   * @param {CampBookingCreateManyArgs} args - Arguments to create many CampBookings.
   * @example
   * // Create many CampBookings
   * const campBooking = await prisma.campBooking.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CampBookingCreateManyArgs>(args?: Prisma.SelectSubset<T, CampBookingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CampBookings and returns the data saved in the database.
   * @param {CampBookingCreateManyAndReturnArgs} args - Arguments to create many CampBookings.
   * @example
   * // Create many CampBookings
   * const campBooking = await prisma.campBooking.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CampBookings and only return the `id`
   * const campBookingWithIdOnly = await prisma.campBooking.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CampBookingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CampBookingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CampBooking.
   * @param {CampBookingDeleteArgs} args - Arguments to delete one CampBooking.
   * @example
   * // Delete one CampBooking
   * const CampBooking = await prisma.campBooking.delete({
   *   where: {
   *     // ... filter to delete one CampBooking
   *   }
   * })
   * 
   */
  delete<T extends CampBookingDeleteArgs>(args: Prisma.SelectSubset<T, CampBookingDeleteArgs<ExtArgs>>): Prisma.Prisma__CampBookingClient<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CampBooking.
   * @param {CampBookingUpdateArgs} args - Arguments to update one CampBooking.
   * @example
   * // Update one CampBooking
   * const campBooking = await prisma.campBooking.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CampBookingUpdateArgs>(args: Prisma.SelectSubset<T, CampBookingUpdateArgs<ExtArgs>>): Prisma.Prisma__CampBookingClient<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CampBookings.
   * @param {CampBookingDeleteManyArgs} args - Arguments to filter CampBookings to delete.
   * @example
   * // Delete a few CampBookings
   * const { count } = await prisma.campBooking.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CampBookingDeleteManyArgs>(args?: Prisma.SelectSubset<T, CampBookingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CampBookings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampBookingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CampBookings
   * const campBooking = await prisma.campBooking.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CampBookingUpdateManyArgs>(args: Prisma.SelectSubset<T, CampBookingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CampBookings and returns the data updated in the database.
   * @param {CampBookingUpdateManyAndReturnArgs} args - Arguments to update many CampBookings.
   * @example
   * // Update many CampBookings
   * const campBooking = await prisma.campBooking.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CampBookings and only return the `id`
   * const campBookingWithIdOnly = await prisma.campBooking.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CampBookingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CampBookingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CampBooking.
   * @param {CampBookingUpsertArgs} args - Arguments to update or create a CampBooking.
   * @example
   * // Update or create a CampBooking
   * const campBooking = await prisma.campBooking.upsert({
   *   create: {
   *     // ... data to create a CampBooking
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CampBooking we want to update
   *   }
   * })
   */
  upsert<T extends CampBookingUpsertArgs>(args: Prisma.SelectSubset<T, CampBookingUpsertArgs<ExtArgs>>): Prisma.Prisma__CampBookingClient<runtime.Types.Result.GetResult<Prisma.$CampBookingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CampBookings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampBookingCountArgs} args - Arguments to filter CampBookings to count.
   * @example
   * // Count the number of CampBookings
   * const count = await prisma.campBooking.count({
   *   where: {
   *     // ... the filter for the CampBookings we want to count
   *   }
   * })
  **/
  count<T extends CampBookingCountArgs>(
    args?: Prisma.Subset<T, CampBookingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CampBookingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CampBooking.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampBookingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CampBookingAggregateArgs>(args: Prisma.Subset<T, CampBookingAggregateArgs>): Prisma.PrismaPromise<GetCampBookingAggregateType<T>>

  /**
   * Group by CampBooking.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CampBookingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CampBookingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CampBookingGroupByArgs['orderBy'] }
      : { orderBy?: CampBookingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CampBookingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCampBookingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CampBooking model
 */
readonly fields: CampBookingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CampBooking.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CampBookingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  camp<T extends Prisma.CampDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CampDefaultArgs<ExtArgs>>): Prisma.Prisma__CampClient<runtime.Types.Result.GetResult<Prisma.$CampPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CampBooking model
 */
export interface CampBookingFieldRefs {
  readonly id: Prisma.FieldRef<"CampBooking", 'String'>
  readonly campId: Prisma.FieldRef<"CampBooking", 'String'>
  readonly userId: Prisma.FieldRef<"CampBooking", 'String'>
  readonly status: Prisma.FieldRef<"CampBooking", 'BookingStatus'>
  readonly amountPaid: Prisma.FieldRef<"CampBooking", 'Float'>
  readonly currency: Prisma.FieldRef<"CampBooking", 'String'>
  readonly stripePaymentId: Prisma.FieldRef<"CampBooking", 'String'>
  readonly createdAt: Prisma.FieldRef<"CampBooking", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CampBooking", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CampBooking findUnique
 */
export type CampBookingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * Filter, which CampBooking to fetch.
   */
  where: Prisma.CampBookingWhereUniqueInput
}

/**
 * CampBooking findUniqueOrThrow
 */
export type CampBookingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * Filter, which CampBooking to fetch.
   */
  where: Prisma.CampBookingWhereUniqueInput
}

/**
 * CampBooking findFirst
 */
export type CampBookingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * Filter, which CampBooking to fetch.
   */
  where?: Prisma.CampBookingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CampBookings to fetch.
   */
  orderBy?: Prisma.CampBookingOrderByWithRelationInput | Prisma.CampBookingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CampBookings.
   */
  cursor?: Prisma.CampBookingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CampBookings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CampBookings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CampBookings.
   */
  distinct?: Prisma.CampBookingScalarFieldEnum | Prisma.CampBookingScalarFieldEnum[]
}

/**
 * CampBooking findFirstOrThrow
 */
export type CampBookingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * Filter, which CampBooking to fetch.
   */
  where?: Prisma.CampBookingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CampBookings to fetch.
   */
  orderBy?: Prisma.CampBookingOrderByWithRelationInput | Prisma.CampBookingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CampBookings.
   */
  cursor?: Prisma.CampBookingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CampBookings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CampBookings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CampBookings.
   */
  distinct?: Prisma.CampBookingScalarFieldEnum | Prisma.CampBookingScalarFieldEnum[]
}

/**
 * CampBooking findMany
 */
export type CampBookingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * Filter, which CampBookings to fetch.
   */
  where?: Prisma.CampBookingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CampBookings to fetch.
   */
  orderBy?: Prisma.CampBookingOrderByWithRelationInput | Prisma.CampBookingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CampBookings.
   */
  cursor?: Prisma.CampBookingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CampBookings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CampBookings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CampBookings.
   */
  distinct?: Prisma.CampBookingScalarFieldEnum | Prisma.CampBookingScalarFieldEnum[]
}

/**
 * CampBooking create
 */
export type CampBookingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * The data needed to create a CampBooking.
   */
  data: Prisma.XOR<Prisma.CampBookingCreateInput, Prisma.CampBookingUncheckedCreateInput>
}

/**
 * CampBooking createMany
 */
export type CampBookingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CampBookings.
   */
  data: Prisma.CampBookingCreateManyInput | Prisma.CampBookingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CampBooking createManyAndReturn
 */
export type CampBookingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * The data used to create many CampBookings.
   */
  data: Prisma.CampBookingCreateManyInput | Prisma.CampBookingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CampBooking update
 */
export type CampBookingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * The data needed to update a CampBooking.
   */
  data: Prisma.XOR<Prisma.CampBookingUpdateInput, Prisma.CampBookingUncheckedUpdateInput>
  /**
   * Choose, which CampBooking to update.
   */
  where: Prisma.CampBookingWhereUniqueInput
}

/**
 * CampBooking updateMany
 */
export type CampBookingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CampBookings.
   */
  data: Prisma.XOR<Prisma.CampBookingUpdateManyMutationInput, Prisma.CampBookingUncheckedUpdateManyInput>
  /**
   * Filter which CampBookings to update
   */
  where?: Prisma.CampBookingWhereInput
  /**
   * Limit how many CampBookings to update.
   */
  limit?: number
}

/**
 * CampBooking updateManyAndReturn
 */
export type CampBookingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * The data used to update CampBookings.
   */
  data: Prisma.XOR<Prisma.CampBookingUpdateManyMutationInput, Prisma.CampBookingUncheckedUpdateManyInput>
  /**
   * Filter which CampBookings to update
   */
  where?: Prisma.CampBookingWhereInput
  /**
   * Limit how many CampBookings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CampBooking upsert
 */
export type CampBookingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * The filter to search for the CampBooking to update in case it exists.
   */
  where: Prisma.CampBookingWhereUniqueInput
  /**
   * In case the CampBooking found by the `where` argument doesn't exist, create a new CampBooking with this data.
   */
  create: Prisma.XOR<Prisma.CampBookingCreateInput, Prisma.CampBookingUncheckedCreateInput>
  /**
   * In case the CampBooking was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CampBookingUpdateInput, Prisma.CampBookingUncheckedUpdateInput>
}

/**
 * CampBooking delete
 */
export type CampBookingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
  /**
   * Filter which CampBooking to delete.
   */
  where: Prisma.CampBookingWhereUniqueInput
}

/**
 * CampBooking deleteMany
 */
export type CampBookingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CampBookings to delete
   */
  where?: Prisma.CampBookingWhereInput
  /**
   * Limit how many CampBookings to delete.
   */
  limit?: number
}

/**
 * CampBooking without action
 */
export type CampBookingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CampBooking
   */
  select?: Prisma.CampBookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CampBooking
   */
  omit?: Prisma.CampBookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CampBookingInclude<ExtArgs> | null
}
