
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Lead` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Lead
 * 
 */
export type LeadModel = runtime.Types.Result.DefaultSelection<Prisma.$LeadPayload>

export type AggregateLead = {
  _count: LeadCountAggregateOutputType | null
  _min: LeadMinAggregateOutputType | null
  _max: LeadMaxAggregateOutputType | null
}

export type LeadMinAggregateOutputType = {
  id: string | null
  schoolId: string | null
  name: string | null
  email: string | null
  phone: string | null
  source: $Enums.LeadSource | null
  status: $Enums.LeadStatus | null
  message: string | null
  interestedIn: string | null
  convertedUserId: string | null
  convertedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LeadMaxAggregateOutputType = {
  id: string | null
  schoolId: string | null
  name: string | null
  email: string | null
  phone: string | null
  source: $Enums.LeadSource | null
  status: $Enums.LeadStatus | null
  message: string | null
  interestedIn: string | null
  convertedUserId: string | null
  convertedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LeadCountAggregateOutputType = {
  id: number
  schoolId: number
  name: number
  email: number
  phone: number
  source: number
  status: number
  message: number
  interestedIn: number
  convertedUserId: number
  convertedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LeadMinAggregateInputType = {
  id?: true
  schoolId?: true
  name?: true
  email?: true
  phone?: true
  source?: true
  status?: true
  message?: true
  interestedIn?: true
  convertedUserId?: true
  convertedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type LeadMaxAggregateInputType = {
  id?: true
  schoolId?: true
  name?: true
  email?: true
  phone?: true
  source?: true
  status?: true
  message?: true
  interestedIn?: true
  convertedUserId?: true
  convertedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type LeadCountAggregateInputType = {
  id?: true
  schoolId?: true
  name?: true
  email?: true
  phone?: true
  source?: true
  status?: true
  message?: true
  interestedIn?: true
  convertedUserId?: true
  convertedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LeadAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Lead to aggregate.
   */
  where?: Prisma.LeadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leads to fetch.
   */
  orderBy?: Prisma.LeadOrderByWithRelationInput | Prisma.LeadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LeadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Leads
  **/
  _count?: true | LeadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LeadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LeadMaxAggregateInputType
}

export type GetLeadAggregateType<T extends LeadAggregateArgs> = {
      [P in keyof T & keyof AggregateLead]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLead[P]>
    : Prisma.GetScalarType<T[P], AggregateLead[P]>
}




export type LeadGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeadWhereInput
  orderBy?: Prisma.LeadOrderByWithAggregationInput | Prisma.LeadOrderByWithAggregationInput[]
  by: Prisma.LeadScalarFieldEnum[] | Prisma.LeadScalarFieldEnum
  having?: Prisma.LeadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LeadCountAggregateInputType | true
  _min?: LeadMinAggregateInputType
  _max?: LeadMaxAggregateInputType
}

export type LeadGroupByOutputType = {
  id: string
  schoolId: string
  name: string
  email: string | null
  phone: string | null
  source: $Enums.LeadSource
  status: $Enums.LeadStatus
  message: string | null
  interestedIn: string | null
  convertedUserId: string | null
  convertedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: LeadCountAggregateOutputType | null
  _min: LeadMinAggregateOutputType | null
  _max: LeadMaxAggregateOutputType | null
}

export type GetLeadGroupByPayload<T extends LeadGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LeadGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LeadGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LeadGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LeadGroupByOutputType[P]>
      }
    >
  >



export type LeadWhereInput = {
  AND?: Prisma.LeadWhereInput | Prisma.LeadWhereInput[]
  OR?: Prisma.LeadWhereInput[]
  NOT?: Prisma.LeadWhereInput | Prisma.LeadWhereInput[]
  id?: Prisma.StringFilter<"Lead"> | string
  schoolId?: Prisma.StringFilter<"Lead"> | string
  name?: Prisma.StringFilter<"Lead"> | string
  email?: Prisma.StringNullableFilter<"Lead"> | string | null
  phone?: Prisma.StringNullableFilter<"Lead"> | string | null
  source?: Prisma.EnumLeadSourceFilter<"Lead"> | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFilter<"Lead"> | $Enums.LeadStatus
  message?: Prisma.StringNullableFilter<"Lead"> | string | null
  interestedIn?: Prisma.StringNullableFilter<"Lead"> | string | null
  convertedUserId?: Prisma.StringNullableFilter<"Lead"> | string | null
  convertedAt?: Prisma.DateTimeNullableFilter<"Lead"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Lead"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Lead"> | Date | string
  school?: Prisma.XOR<Prisma.SchoolScalarRelationFilter, Prisma.SchoolWhereInput>
  convertedUser?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  notes?: Prisma.LeadNoteListRelationFilter
}

export type LeadOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  interestedIn?: Prisma.SortOrderInput | Prisma.SortOrder
  convertedUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  convertedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  school?: Prisma.SchoolOrderByWithRelationInput
  convertedUser?: Prisma.UserOrderByWithRelationInput
  notes?: Prisma.LeadNoteOrderByRelationAggregateInput
}

export type LeadWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LeadWhereInput | Prisma.LeadWhereInput[]
  OR?: Prisma.LeadWhereInput[]
  NOT?: Prisma.LeadWhereInput | Prisma.LeadWhereInput[]
  schoolId?: Prisma.StringFilter<"Lead"> | string
  name?: Prisma.StringFilter<"Lead"> | string
  email?: Prisma.StringNullableFilter<"Lead"> | string | null
  phone?: Prisma.StringNullableFilter<"Lead"> | string | null
  source?: Prisma.EnumLeadSourceFilter<"Lead"> | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFilter<"Lead"> | $Enums.LeadStatus
  message?: Prisma.StringNullableFilter<"Lead"> | string | null
  interestedIn?: Prisma.StringNullableFilter<"Lead"> | string | null
  convertedUserId?: Prisma.StringNullableFilter<"Lead"> | string | null
  convertedAt?: Prisma.DateTimeNullableFilter<"Lead"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Lead"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Lead"> | Date | string
  school?: Prisma.XOR<Prisma.SchoolScalarRelationFilter, Prisma.SchoolWhereInput>
  convertedUser?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  notes?: Prisma.LeadNoteListRelationFilter
}, "id">

export type LeadOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  interestedIn?: Prisma.SortOrderInput | Prisma.SortOrder
  convertedUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  convertedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LeadCountOrderByAggregateInput
  _max?: Prisma.LeadMaxOrderByAggregateInput
  _min?: Prisma.LeadMinOrderByAggregateInput
}

export type LeadScalarWhereWithAggregatesInput = {
  AND?: Prisma.LeadScalarWhereWithAggregatesInput | Prisma.LeadScalarWhereWithAggregatesInput[]
  OR?: Prisma.LeadScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LeadScalarWhereWithAggregatesInput | Prisma.LeadScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Lead"> | string
  schoolId?: Prisma.StringWithAggregatesFilter<"Lead"> | string
  name?: Prisma.StringWithAggregatesFilter<"Lead"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"Lead"> | string | null
  phone?: Prisma.StringNullableWithAggregatesFilter<"Lead"> | string | null
  source?: Prisma.EnumLeadSourceWithAggregatesFilter<"Lead"> | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusWithAggregatesFilter<"Lead"> | $Enums.LeadStatus
  message?: Prisma.StringNullableWithAggregatesFilter<"Lead"> | string | null
  interestedIn?: Prisma.StringNullableWithAggregatesFilter<"Lead"> | string | null
  convertedUserId?: Prisma.StringNullableWithAggregatesFilter<"Lead"> | string | null
  convertedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Lead"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Lead"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Lead"> | Date | string
}

export type LeadCreateInput = {
  id?: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  school: Prisma.SchoolCreateNestedOneWithoutLeadsInput
  convertedUser?: Prisma.UserCreateNestedOneWithoutLeadsInput
  notes?: Prisma.LeadNoteCreateNestedManyWithoutLeadInput
}

export type LeadUncheckedCreateInput = {
  id?: string
  schoolId: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedUserId?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  notes?: Prisma.LeadNoteUncheckedCreateNestedManyWithoutLeadInput
}

export type LeadUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  school?: Prisma.SchoolUpdateOneRequiredWithoutLeadsNestedInput
  convertedUser?: Prisma.UserUpdateOneWithoutLeadsNestedInput
  notes?: Prisma.LeadNoteUpdateManyWithoutLeadNestedInput
}

export type LeadUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.LeadNoteUncheckedUpdateManyWithoutLeadNestedInput
}

export type LeadCreateManyInput = {
  id?: string
  schoolId: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedUserId?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeadUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeadUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeadListRelationFilter = {
  every?: Prisma.LeadWhereInput
  some?: Prisma.LeadWhereInput
  none?: Prisma.LeadWhereInput
}

export type LeadOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LeadCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  message?: Prisma.SortOrder
  interestedIn?: Prisma.SortOrder
  convertedUserId?: Prisma.SortOrder
  convertedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeadMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  message?: Prisma.SortOrder
  interestedIn?: Prisma.SortOrder
  convertedUserId?: Prisma.SortOrder
  convertedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeadMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  message?: Prisma.SortOrder
  interestedIn?: Prisma.SortOrder
  convertedUserId?: Prisma.SortOrder
  convertedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeadScalarRelationFilter = {
  is?: Prisma.LeadWhereInput
  isNot?: Prisma.LeadWhereInput
}

export type LeadCreateNestedManyWithoutConvertedUserInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutConvertedUserInput, Prisma.LeadUncheckedCreateWithoutConvertedUserInput> | Prisma.LeadCreateWithoutConvertedUserInput[] | Prisma.LeadUncheckedCreateWithoutConvertedUserInput[]
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutConvertedUserInput | Prisma.LeadCreateOrConnectWithoutConvertedUserInput[]
  createMany?: Prisma.LeadCreateManyConvertedUserInputEnvelope
  connect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
}

export type LeadUncheckedCreateNestedManyWithoutConvertedUserInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutConvertedUserInput, Prisma.LeadUncheckedCreateWithoutConvertedUserInput> | Prisma.LeadCreateWithoutConvertedUserInput[] | Prisma.LeadUncheckedCreateWithoutConvertedUserInput[]
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutConvertedUserInput | Prisma.LeadCreateOrConnectWithoutConvertedUserInput[]
  createMany?: Prisma.LeadCreateManyConvertedUserInputEnvelope
  connect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
}

export type LeadUpdateManyWithoutConvertedUserNestedInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutConvertedUserInput, Prisma.LeadUncheckedCreateWithoutConvertedUserInput> | Prisma.LeadCreateWithoutConvertedUserInput[] | Prisma.LeadUncheckedCreateWithoutConvertedUserInput[]
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutConvertedUserInput | Prisma.LeadCreateOrConnectWithoutConvertedUserInput[]
  upsert?: Prisma.LeadUpsertWithWhereUniqueWithoutConvertedUserInput | Prisma.LeadUpsertWithWhereUniqueWithoutConvertedUserInput[]
  createMany?: Prisma.LeadCreateManyConvertedUserInputEnvelope
  set?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  disconnect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  delete?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  connect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  update?: Prisma.LeadUpdateWithWhereUniqueWithoutConvertedUserInput | Prisma.LeadUpdateWithWhereUniqueWithoutConvertedUserInput[]
  updateMany?: Prisma.LeadUpdateManyWithWhereWithoutConvertedUserInput | Prisma.LeadUpdateManyWithWhereWithoutConvertedUserInput[]
  deleteMany?: Prisma.LeadScalarWhereInput | Prisma.LeadScalarWhereInput[]
}

export type LeadUncheckedUpdateManyWithoutConvertedUserNestedInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutConvertedUserInput, Prisma.LeadUncheckedCreateWithoutConvertedUserInput> | Prisma.LeadCreateWithoutConvertedUserInput[] | Prisma.LeadUncheckedCreateWithoutConvertedUserInput[]
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutConvertedUserInput | Prisma.LeadCreateOrConnectWithoutConvertedUserInput[]
  upsert?: Prisma.LeadUpsertWithWhereUniqueWithoutConvertedUserInput | Prisma.LeadUpsertWithWhereUniqueWithoutConvertedUserInput[]
  createMany?: Prisma.LeadCreateManyConvertedUserInputEnvelope
  set?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  disconnect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  delete?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  connect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  update?: Prisma.LeadUpdateWithWhereUniqueWithoutConvertedUserInput | Prisma.LeadUpdateWithWhereUniqueWithoutConvertedUserInput[]
  updateMany?: Prisma.LeadUpdateManyWithWhereWithoutConvertedUserInput | Prisma.LeadUpdateManyWithWhereWithoutConvertedUserInput[]
  deleteMany?: Prisma.LeadScalarWhereInput | Prisma.LeadScalarWhereInput[]
}

export type LeadCreateNestedManyWithoutSchoolInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutSchoolInput, Prisma.LeadUncheckedCreateWithoutSchoolInput> | Prisma.LeadCreateWithoutSchoolInput[] | Prisma.LeadUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutSchoolInput | Prisma.LeadCreateOrConnectWithoutSchoolInput[]
  createMany?: Prisma.LeadCreateManySchoolInputEnvelope
  connect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
}

export type LeadUncheckedCreateNestedManyWithoutSchoolInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutSchoolInput, Prisma.LeadUncheckedCreateWithoutSchoolInput> | Prisma.LeadCreateWithoutSchoolInput[] | Prisma.LeadUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutSchoolInput | Prisma.LeadCreateOrConnectWithoutSchoolInput[]
  createMany?: Prisma.LeadCreateManySchoolInputEnvelope
  connect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
}

export type LeadUpdateManyWithoutSchoolNestedInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutSchoolInput, Prisma.LeadUncheckedCreateWithoutSchoolInput> | Prisma.LeadCreateWithoutSchoolInput[] | Prisma.LeadUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutSchoolInput | Prisma.LeadCreateOrConnectWithoutSchoolInput[]
  upsert?: Prisma.LeadUpsertWithWhereUniqueWithoutSchoolInput | Prisma.LeadUpsertWithWhereUniqueWithoutSchoolInput[]
  createMany?: Prisma.LeadCreateManySchoolInputEnvelope
  set?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  disconnect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  delete?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  connect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  update?: Prisma.LeadUpdateWithWhereUniqueWithoutSchoolInput | Prisma.LeadUpdateWithWhereUniqueWithoutSchoolInput[]
  updateMany?: Prisma.LeadUpdateManyWithWhereWithoutSchoolInput | Prisma.LeadUpdateManyWithWhereWithoutSchoolInput[]
  deleteMany?: Prisma.LeadScalarWhereInput | Prisma.LeadScalarWhereInput[]
}

export type LeadUncheckedUpdateManyWithoutSchoolNestedInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutSchoolInput, Prisma.LeadUncheckedCreateWithoutSchoolInput> | Prisma.LeadCreateWithoutSchoolInput[] | Prisma.LeadUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutSchoolInput | Prisma.LeadCreateOrConnectWithoutSchoolInput[]
  upsert?: Prisma.LeadUpsertWithWhereUniqueWithoutSchoolInput | Prisma.LeadUpsertWithWhereUniqueWithoutSchoolInput[]
  createMany?: Prisma.LeadCreateManySchoolInputEnvelope
  set?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  disconnect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  delete?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  connect?: Prisma.LeadWhereUniqueInput | Prisma.LeadWhereUniqueInput[]
  update?: Prisma.LeadUpdateWithWhereUniqueWithoutSchoolInput | Prisma.LeadUpdateWithWhereUniqueWithoutSchoolInput[]
  updateMany?: Prisma.LeadUpdateManyWithWhereWithoutSchoolInput | Prisma.LeadUpdateManyWithWhereWithoutSchoolInput[]
  deleteMany?: Prisma.LeadScalarWhereInput | Prisma.LeadScalarWhereInput[]
}

export type EnumLeadSourceFieldUpdateOperationsInput = {
  set?: $Enums.LeadSource
}

export type EnumLeadStatusFieldUpdateOperationsInput = {
  set?: $Enums.LeadStatus
}

export type LeadCreateNestedOneWithoutNotesInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutNotesInput, Prisma.LeadUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutNotesInput
  connect?: Prisma.LeadWhereUniqueInput
}

export type LeadUpdateOneRequiredWithoutNotesNestedInput = {
  create?: Prisma.XOR<Prisma.LeadCreateWithoutNotesInput, Prisma.LeadUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.LeadCreateOrConnectWithoutNotesInput
  upsert?: Prisma.LeadUpsertWithoutNotesInput
  connect?: Prisma.LeadWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeadUpdateToOneWithWhereWithoutNotesInput, Prisma.LeadUpdateWithoutNotesInput>, Prisma.LeadUncheckedUpdateWithoutNotesInput>
}

export type LeadCreateWithoutConvertedUserInput = {
  id?: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  school: Prisma.SchoolCreateNestedOneWithoutLeadsInput
  notes?: Prisma.LeadNoteCreateNestedManyWithoutLeadInput
}

export type LeadUncheckedCreateWithoutConvertedUserInput = {
  id?: string
  schoolId: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  notes?: Prisma.LeadNoteUncheckedCreateNestedManyWithoutLeadInput
}

export type LeadCreateOrConnectWithoutConvertedUserInput = {
  where: Prisma.LeadWhereUniqueInput
  create: Prisma.XOR<Prisma.LeadCreateWithoutConvertedUserInput, Prisma.LeadUncheckedCreateWithoutConvertedUserInput>
}

export type LeadCreateManyConvertedUserInputEnvelope = {
  data: Prisma.LeadCreateManyConvertedUserInput | Prisma.LeadCreateManyConvertedUserInput[]
  skipDuplicates?: boolean
}

export type LeadUpsertWithWhereUniqueWithoutConvertedUserInput = {
  where: Prisma.LeadWhereUniqueInput
  update: Prisma.XOR<Prisma.LeadUpdateWithoutConvertedUserInput, Prisma.LeadUncheckedUpdateWithoutConvertedUserInput>
  create: Prisma.XOR<Prisma.LeadCreateWithoutConvertedUserInput, Prisma.LeadUncheckedCreateWithoutConvertedUserInput>
}

export type LeadUpdateWithWhereUniqueWithoutConvertedUserInput = {
  where: Prisma.LeadWhereUniqueInput
  data: Prisma.XOR<Prisma.LeadUpdateWithoutConvertedUserInput, Prisma.LeadUncheckedUpdateWithoutConvertedUserInput>
}

export type LeadUpdateManyWithWhereWithoutConvertedUserInput = {
  where: Prisma.LeadScalarWhereInput
  data: Prisma.XOR<Prisma.LeadUpdateManyMutationInput, Prisma.LeadUncheckedUpdateManyWithoutConvertedUserInput>
}

export type LeadScalarWhereInput = {
  AND?: Prisma.LeadScalarWhereInput | Prisma.LeadScalarWhereInput[]
  OR?: Prisma.LeadScalarWhereInput[]
  NOT?: Prisma.LeadScalarWhereInput | Prisma.LeadScalarWhereInput[]
  id?: Prisma.StringFilter<"Lead"> | string
  schoolId?: Prisma.StringFilter<"Lead"> | string
  name?: Prisma.StringFilter<"Lead"> | string
  email?: Prisma.StringNullableFilter<"Lead"> | string | null
  phone?: Prisma.StringNullableFilter<"Lead"> | string | null
  source?: Prisma.EnumLeadSourceFilter<"Lead"> | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFilter<"Lead"> | $Enums.LeadStatus
  message?: Prisma.StringNullableFilter<"Lead"> | string | null
  interestedIn?: Prisma.StringNullableFilter<"Lead"> | string | null
  convertedUserId?: Prisma.StringNullableFilter<"Lead"> | string | null
  convertedAt?: Prisma.DateTimeNullableFilter<"Lead"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Lead"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Lead"> | Date | string
}

export type LeadCreateWithoutSchoolInput = {
  id?: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  convertedUser?: Prisma.UserCreateNestedOneWithoutLeadsInput
  notes?: Prisma.LeadNoteCreateNestedManyWithoutLeadInput
}

export type LeadUncheckedCreateWithoutSchoolInput = {
  id?: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedUserId?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  notes?: Prisma.LeadNoteUncheckedCreateNestedManyWithoutLeadInput
}

export type LeadCreateOrConnectWithoutSchoolInput = {
  where: Prisma.LeadWhereUniqueInput
  create: Prisma.XOR<Prisma.LeadCreateWithoutSchoolInput, Prisma.LeadUncheckedCreateWithoutSchoolInput>
}

export type LeadCreateManySchoolInputEnvelope = {
  data: Prisma.LeadCreateManySchoolInput | Prisma.LeadCreateManySchoolInput[]
  skipDuplicates?: boolean
}

export type LeadUpsertWithWhereUniqueWithoutSchoolInput = {
  where: Prisma.LeadWhereUniqueInput
  update: Prisma.XOR<Prisma.LeadUpdateWithoutSchoolInput, Prisma.LeadUncheckedUpdateWithoutSchoolInput>
  create: Prisma.XOR<Prisma.LeadCreateWithoutSchoolInput, Prisma.LeadUncheckedCreateWithoutSchoolInput>
}

export type LeadUpdateWithWhereUniqueWithoutSchoolInput = {
  where: Prisma.LeadWhereUniqueInput
  data: Prisma.XOR<Prisma.LeadUpdateWithoutSchoolInput, Prisma.LeadUncheckedUpdateWithoutSchoolInput>
}

export type LeadUpdateManyWithWhereWithoutSchoolInput = {
  where: Prisma.LeadScalarWhereInput
  data: Prisma.XOR<Prisma.LeadUpdateManyMutationInput, Prisma.LeadUncheckedUpdateManyWithoutSchoolInput>
}

export type LeadCreateWithoutNotesInput = {
  id?: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  school: Prisma.SchoolCreateNestedOneWithoutLeadsInput
  convertedUser?: Prisma.UserCreateNestedOneWithoutLeadsInput
}

export type LeadUncheckedCreateWithoutNotesInput = {
  id?: string
  schoolId: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedUserId?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeadCreateOrConnectWithoutNotesInput = {
  where: Prisma.LeadWhereUniqueInput
  create: Prisma.XOR<Prisma.LeadCreateWithoutNotesInput, Prisma.LeadUncheckedCreateWithoutNotesInput>
}

export type LeadUpsertWithoutNotesInput = {
  update: Prisma.XOR<Prisma.LeadUpdateWithoutNotesInput, Prisma.LeadUncheckedUpdateWithoutNotesInput>
  create: Prisma.XOR<Prisma.LeadCreateWithoutNotesInput, Prisma.LeadUncheckedCreateWithoutNotesInput>
  where?: Prisma.LeadWhereInput
}

export type LeadUpdateToOneWithWhereWithoutNotesInput = {
  where?: Prisma.LeadWhereInput
  data: Prisma.XOR<Prisma.LeadUpdateWithoutNotesInput, Prisma.LeadUncheckedUpdateWithoutNotesInput>
}

export type LeadUpdateWithoutNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  school?: Prisma.SchoolUpdateOneRequiredWithoutLeadsNestedInput
  convertedUser?: Prisma.UserUpdateOneWithoutLeadsNestedInput
}

export type LeadUncheckedUpdateWithoutNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeadCreateManyConvertedUserInput = {
  id?: string
  schoolId: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeadUpdateWithoutConvertedUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  school?: Prisma.SchoolUpdateOneRequiredWithoutLeadsNestedInput
  notes?: Prisma.LeadNoteUpdateManyWithoutLeadNestedInput
}

export type LeadUncheckedUpdateWithoutConvertedUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.LeadNoteUncheckedUpdateManyWithoutLeadNestedInput
}

export type LeadUncheckedUpdateManyWithoutConvertedUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeadCreateManySchoolInput = {
  id?: string
  name: string
  email?: string | null
  phone?: string | null
  source?: $Enums.LeadSource
  status?: $Enums.LeadStatus
  message?: string | null
  interestedIn?: string | null
  convertedUserId?: string | null
  convertedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LeadUpdateWithoutSchoolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  convertedUser?: Prisma.UserUpdateOneWithoutLeadsNestedInput
  notes?: Prisma.LeadNoteUpdateManyWithoutLeadNestedInput
}

export type LeadUncheckedUpdateWithoutSchoolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notes?: Prisma.LeadNoteUncheckedUpdateManyWithoutLeadNestedInput
}

export type LeadUncheckedUpdateManyWithoutSchoolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.EnumLeadSourceFieldUpdateOperationsInput | $Enums.LeadSource
  status?: Prisma.EnumLeadStatusFieldUpdateOperationsInput | $Enums.LeadStatus
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interestedIn?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  convertedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type LeadCountOutputType
 */

export type LeadCountOutputType = {
  notes: number
}

export type LeadCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  notes?: boolean | LeadCountOutputTypeCountNotesArgs
}

/**
 * LeadCountOutputType without action
 */
export type LeadCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeadCountOutputType
   */
  select?: Prisma.LeadCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LeadCountOutputType without action
 */
export type LeadCountOutputTypeCountNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeadNoteWhereInput
}


export type LeadSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  schoolId?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  source?: boolean
  status?: boolean
  message?: boolean
  interestedIn?: boolean
  convertedUserId?: boolean
  convertedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  convertedUser?: boolean | Prisma.Lead$convertedUserArgs<ExtArgs>
  notes?: boolean | Prisma.Lead$notesArgs<ExtArgs>
  _count?: boolean | Prisma.LeadCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lead"]>

export type LeadSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  schoolId?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  source?: boolean
  status?: boolean
  message?: boolean
  interestedIn?: boolean
  convertedUserId?: boolean
  convertedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  convertedUser?: boolean | Prisma.Lead$convertedUserArgs<ExtArgs>
}, ExtArgs["result"]["lead"]>

export type LeadSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  schoolId?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  source?: boolean
  status?: boolean
  message?: boolean
  interestedIn?: boolean
  convertedUserId?: boolean
  convertedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  convertedUser?: boolean | Prisma.Lead$convertedUserArgs<ExtArgs>
}, ExtArgs["result"]["lead"]>

export type LeadSelectScalar = {
  id?: boolean
  schoolId?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  source?: boolean
  status?: boolean
  message?: boolean
  interestedIn?: boolean
  convertedUserId?: boolean
  convertedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LeadOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "schoolId" | "name" | "email" | "phone" | "source" | "status" | "message" | "interestedIn" | "convertedUserId" | "convertedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["lead"]>
export type LeadInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  convertedUser?: boolean | Prisma.Lead$convertedUserArgs<ExtArgs>
  notes?: boolean | Prisma.Lead$notesArgs<ExtArgs>
  _count?: boolean | Prisma.LeadCountOutputTypeDefaultArgs<ExtArgs>
}
export type LeadIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  convertedUser?: boolean | Prisma.Lead$convertedUserArgs<ExtArgs>
}
export type LeadIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  convertedUser?: boolean | Prisma.Lead$convertedUserArgs<ExtArgs>
}

export type $LeadPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Lead"
  objects: {
    school: Prisma.$SchoolPayload<ExtArgs>
    convertedUser: Prisma.$UserPayload<ExtArgs> | null
    notes: Prisma.$LeadNotePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    schoolId: string
    name: string
    email: string | null
    phone: string | null
    source: $Enums.LeadSource
    status: $Enums.LeadStatus
    message: string | null
    interestedIn: string | null
    convertedUserId: string | null
    convertedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["lead"]>
  composites: {}
}

export type LeadGetPayload<S extends boolean | null | undefined | LeadDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LeadPayload, S>

export type LeadCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LeadFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LeadCountAggregateInputType | true
  }

export interface LeadDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Lead'], meta: { name: 'Lead' } }
  /**
   * Find zero or one Lead that matches the filter.
   * @param {LeadFindUniqueArgs} args - Arguments to find a Lead
   * @example
   * // Get one Lead
   * const lead = await prisma.lead.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LeadFindUniqueArgs>(args: Prisma.SelectSubset<T, LeadFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Lead that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LeadFindUniqueOrThrowArgs} args - Arguments to find a Lead
   * @example
   * // Get one Lead
   * const lead = await prisma.lead.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LeadFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LeadFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lead that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeadFindFirstArgs} args - Arguments to find a Lead
   * @example
   * // Get one Lead
   * const lead = await prisma.lead.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LeadFindFirstArgs>(args?: Prisma.SelectSubset<T, LeadFindFirstArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lead that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeadFindFirstOrThrowArgs} args - Arguments to find a Lead
   * @example
   * // Get one Lead
   * const lead = await prisma.lead.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LeadFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LeadFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Leads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Leads
   * const leads = await prisma.lead.findMany()
   * 
   * // Get first 10 Leads
   * const leads = await prisma.lead.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const leadWithIdOnly = await prisma.lead.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LeadFindManyArgs>(args?: Prisma.SelectSubset<T, LeadFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Lead.
   * @param {LeadCreateArgs} args - Arguments to create a Lead.
   * @example
   * // Create one Lead
   * const Lead = await prisma.lead.create({
   *   data: {
   *     // ... data to create a Lead
   *   }
   * })
   * 
   */
  create<T extends LeadCreateArgs>(args: Prisma.SelectSubset<T, LeadCreateArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Leads.
   * @param {LeadCreateManyArgs} args - Arguments to create many Leads.
   * @example
   * // Create many Leads
   * const lead = await prisma.lead.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LeadCreateManyArgs>(args?: Prisma.SelectSubset<T, LeadCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Leads and returns the data saved in the database.
   * @param {LeadCreateManyAndReturnArgs} args - Arguments to create many Leads.
   * @example
   * // Create many Leads
   * const lead = await prisma.lead.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Leads and only return the `id`
   * const leadWithIdOnly = await prisma.lead.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LeadCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LeadCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Lead.
   * @param {LeadDeleteArgs} args - Arguments to delete one Lead.
   * @example
   * // Delete one Lead
   * const Lead = await prisma.lead.delete({
   *   where: {
   *     // ... filter to delete one Lead
   *   }
   * })
   * 
   */
  delete<T extends LeadDeleteArgs>(args: Prisma.SelectSubset<T, LeadDeleteArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Lead.
   * @param {LeadUpdateArgs} args - Arguments to update one Lead.
   * @example
   * // Update one Lead
   * const lead = await prisma.lead.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LeadUpdateArgs>(args: Prisma.SelectSubset<T, LeadUpdateArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Leads.
   * @param {LeadDeleteManyArgs} args - Arguments to filter Leads to delete.
   * @example
   * // Delete a few Leads
   * const { count } = await prisma.lead.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LeadDeleteManyArgs>(args?: Prisma.SelectSubset<T, LeadDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Leads
   * const lead = await prisma.lead.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LeadUpdateManyArgs>(args: Prisma.SelectSubset<T, LeadUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leads and returns the data updated in the database.
   * @param {LeadUpdateManyAndReturnArgs} args - Arguments to update many Leads.
   * @example
   * // Update many Leads
   * const lead = await prisma.lead.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Leads and only return the `id`
   * const leadWithIdOnly = await prisma.lead.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LeadUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LeadUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Lead.
   * @param {LeadUpsertArgs} args - Arguments to update or create a Lead.
   * @example
   * // Update or create a Lead
   * const lead = await prisma.lead.upsert({
   *   create: {
   *     // ... data to create a Lead
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Lead we want to update
   *   }
   * })
   */
  upsert<T extends LeadUpsertArgs>(args: Prisma.SelectSubset<T, LeadUpsertArgs<ExtArgs>>): Prisma.Prisma__LeadClient<runtime.Types.Result.GetResult<Prisma.$LeadPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Leads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeadCountArgs} args - Arguments to filter Leads to count.
   * @example
   * // Count the number of Leads
   * const count = await prisma.lead.count({
   *   where: {
   *     // ... the filter for the Leads we want to count
   *   }
   * })
  **/
  count<T extends LeadCountArgs>(
    args?: Prisma.Subset<T, LeadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LeadCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Lead.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LeadAggregateArgs>(args: Prisma.Subset<T, LeadAggregateArgs>): Prisma.PrismaPromise<GetLeadAggregateType<T>>

  /**
   * Group by Lead.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LeadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LeadGroupByArgs['orderBy'] }
      : { orderBy?: LeadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LeadGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLeadGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Lead model
 */
readonly fields: LeadFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Lead.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LeadClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  school<T extends Prisma.SchoolDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SchoolDefaultArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  convertedUser<T extends Prisma.Lead$convertedUserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Lead$convertedUserArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  notes<T extends Prisma.Lead$notesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Lead$notesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeadNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Lead model
 */
export interface LeadFieldRefs {
  readonly id: Prisma.FieldRef<"Lead", 'String'>
  readonly schoolId: Prisma.FieldRef<"Lead", 'String'>
  readonly name: Prisma.FieldRef<"Lead", 'String'>
  readonly email: Prisma.FieldRef<"Lead", 'String'>
  readonly phone: Prisma.FieldRef<"Lead", 'String'>
  readonly source: Prisma.FieldRef<"Lead", 'LeadSource'>
  readonly status: Prisma.FieldRef<"Lead", 'LeadStatus'>
  readonly message: Prisma.FieldRef<"Lead", 'String'>
  readonly interestedIn: Prisma.FieldRef<"Lead", 'String'>
  readonly convertedUserId: Prisma.FieldRef<"Lead", 'String'>
  readonly convertedAt: Prisma.FieldRef<"Lead", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Lead", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Lead", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Lead findUnique
 */
export type LeadFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * Filter, which Lead to fetch.
   */
  where: Prisma.LeadWhereUniqueInput
}

/**
 * Lead findUniqueOrThrow
 */
export type LeadFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * Filter, which Lead to fetch.
   */
  where: Prisma.LeadWhereUniqueInput
}

/**
 * Lead findFirst
 */
export type LeadFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * Filter, which Lead to fetch.
   */
  where?: Prisma.LeadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leads to fetch.
   */
  orderBy?: Prisma.LeadOrderByWithRelationInput | Prisma.LeadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leads.
   */
  cursor?: Prisma.LeadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leads.
   */
  distinct?: Prisma.LeadScalarFieldEnum | Prisma.LeadScalarFieldEnum[]
}

/**
 * Lead findFirstOrThrow
 */
export type LeadFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * Filter, which Lead to fetch.
   */
  where?: Prisma.LeadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leads to fetch.
   */
  orderBy?: Prisma.LeadOrderByWithRelationInput | Prisma.LeadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leads.
   */
  cursor?: Prisma.LeadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leads.
   */
  distinct?: Prisma.LeadScalarFieldEnum | Prisma.LeadScalarFieldEnum[]
}

/**
 * Lead findMany
 */
export type LeadFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * Filter, which Leads to fetch.
   */
  where?: Prisma.LeadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leads to fetch.
   */
  orderBy?: Prisma.LeadOrderByWithRelationInput | Prisma.LeadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Leads.
   */
  cursor?: Prisma.LeadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leads.
   */
  distinct?: Prisma.LeadScalarFieldEnum | Prisma.LeadScalarFieldEnum[]
}

/**
 * Lead create
 */
export type LeadCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * The data needed to create a Lead.
   */
  data: Prisma.XOR<Prisma.LeadCreateInput, Prisma.LeadUncheckedCreateInput>
}

/**
 * Lead createMany
 */
export type LeadCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Leads.
   */
  data: Prisma.LeadCreateManyInput | Prisma.LeadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Lead createManyAndReturn
 */
export type LeadCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * The data used to create many Leads.
   */
  data: Prisma.LeadCreateManyInput | Prisma.LeadCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Lead update
 */
export type LeadUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * The data needed to update a Lead.
   */
  data: Prisma.XOR<Prisma.LeadUpdateInput, Prisma.LeadUncheckedUpdateInput>
  /**
   * Choose, which Lead to update.
   */
  where: Prisma.LeadWhereUniqueInput
}

/**
 * Lead updateMany
 */
export type LeadUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Leads.
   */
  data: Prisma.XOR<Prisma.LeadUpdateManyMutationInput, Prisma.LeadUncheckedUpdateManyInput>
  /**
   * Filter which Leads to update
   */
  where?: Prisma.LeadWhereInput
  /**
   * Limit how many Leads to update.
   */
  limit?: number
}

/**
 * Lead updateManyAndReturn
 */
export type LeadUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * The data used to update Leads.
   */
  data: Prisma.XOR<Prisma.LeadUpdateManyMutationInput, Prisma.LeadUncheckedUpdateManyInput>
  /**
   * Filter which Leads to update
   */
  where?: Prisma.LeadWhereInput
  /**
   * Limit how many Leads to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Lead upsert
 */
export type LeadUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * The filter to search for the Lead to update in case it exists.
   */
  where: Prisma.LeadWhereUniqueInput
  /**
   * In case the Lead found by the `where` argument doesn't exist, create a new Lead with this data.
   */
  create: Prisma.XOR<Prisma.LeadCreateInput, Prisma.LeadUncheckedCreateInput>
  /**
   * In case the Lead was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LeadUpdateInput, Prisma.LeadUncheckedUpdateInput>
}

/**
 * Lead delete
 */
export type LeadDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
  /**
   * Filter which Lead to delete.
   */
  where: Prisma.LeadWhereUniqueInput
}

/**
 * Lead deleteMany
 */
export type LeadDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Leads to delete
   */
  where?: Prisma.LeadWhereInput
  /**
   * Limit how many Leads to delete.
   */
  limit?: number
}

/**
 * Lead.convertedUser
 */
export type Lead$convertedUserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Lead.notes
 */
export type Lead$notesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeadNote
   */
  select?: Prisma.LeadNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeadNote
   */
  omit?: Prisma.LeadNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadNoteInclude<ExtArgs> | null
  where?: Prisma.LeadNoteWhereInput
  orderBy?: Prisma.LeadNoteOrderByWithRelationInput | Prisma.LeadNoteOrderByWithRelationInput[]
  cursor?: Prisma.LeadNoteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LeadNoteScalarFieldEnum | Prisma.LeadNoteScalarFieldEnum[]
}

/**
 * Lead without action
 */
export type LeadDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lead
   */
  select?: Prisma.LeadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lead
   */
  omit?: Prisma.LeadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeadInclude<ExtArgs> | null
}
