
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SchoolDiscipline` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SchoolDiscipline
 * 
 */
export type SchoolDisciplineModel = runtime.Types.Result.DefaultSelection<Prisma.$SchoolDisciplinePayload>

export type AggregateSchoolDiscipline = {
  _count: SchoolDisciplineCountAggregateOutputType | null
  _min: SchoolDisciplineMinAggregateOutputType | null
  _max: SchoolDisciplineMaxAggregateOutputType | null
}

export type SchoolDisciplineMinAggregateOutputType = {
  schoolId: string | null
  disciplineId: string | null
}

export type SchoolDisciplineMaxAggregateOutputType = {
  schoolId: string | null
  disciplineId: string | null
}

export type SchoolDisciplineCountAggregateOutputType = {
  schoolId: number
  disciplineId: number
  _all: number
}


export type SchoolDisciplineMinAggregateInputType = {
  schoolId?: true
  disciplineId?: true
}

export type SchoolDisciplineMaxAggregateInputType = {
  schoolId?: true
  disciplineId?: true
}

export type SchoolDisciplineCountAggregateInputType = {
  schoolId?: true
  disciplineId?: true
  _all?: true
}

export type SchoolDisciplineAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SchoolDiscipline to aggregate.
   */
  where?: Prisma.SchoolDisciplineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SchoolDisciplines to fetch.
   */
  orderBy?: Prisma.SchoolDisciplineOrderByWithRelationInput | Prisma.SchoolDisciplineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SchoolDisciplineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SchoolDisciplines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SchoolDisciplines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SchoolDisciplines
  **/
  _count?: true | SchoolDisciplineCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SchoolDisciplineMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SchoolDisciplineMaxAggregateInputType
}

export type GetSchoolDisciplineAggregateType<T extends SchoolDisciplineAggregateArgs> = {
      [P in keyof T & keyof AggregateSchoolDiscipline]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSchoolDiscipline[P]>
    : Prisma.GetScalarType<T[P], AggregateSchoolDiscipline[P]>
}




export type SchoolDisciplineGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SchoolDisciplineWhereInput
  orderBy?: Prisma.SchoolDisciplineOrderByWithAggregationInput | Prisma.SchoolDisciplineOrderByWithAggregationInput[]
  by: Prisma.SchoolDisciplineScalarFieldEnum[] | Prisma.SchoolDisciplineScalarFieldEnum
  having?: Prisma.SchoolDisciplineScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SchoolDisciplineCountAggregateInputType | true
  _min?: SchoolDisciplineMinAggregateInputType
  _max?: SchoolDisciplineMaxAggregateInputType
}

export type SchoolDisciplineGroupByOutputType = {
  schoolId: string
  disciplineId: string
  _count: SchoolDisciplineCountAggregateOutputType | null
  _min: SchoolDisciplineMinAggregateOutputType | null
  _max: SchoolDisciplineMaxAggregateOutputType | null
}

export type GetSchoolDisciplineGroupByPayload<T extends SchoolDisciplineGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SchoolDisciplineGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SchoolDisciplineGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SchoolDisciplineGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SchoolDisciplineGroupByOutputType[P]>
      }
    >
  >



export type SchoolDisciplineWhereInput = {
  AND?: Prisma.SchoolDisciplineWhereInput | Prisma.SchoolDisciplineWhereInput[]
  OR?: Prisma.SchoolDisciplineWhereInput[]
  NOT?: Prisma.SchoolDisciplineWhereInput | Prisma.SchoolDisciplineWhereInput[]
  schoolId?: Prisma.StringFilter<"SchoolDiscipline"> | string
  disciplineId?: Prisma.StringFilter<"SchoolDiscipline"> | string
  school?: Prisma.XOR<Prisma.SchoolScalarRelationFilter, Prisma.SchoolWhereInput>
  discipline?: Prisma.XOR<Prisma.DisciplineScalarRelationFilter, Prisma.DisciplineWhereInput>
}

export type SchoolDisciplineOrderByWithRelationInput = {
  schoolId?: Prisma.SortOrder
  disciplineId?: Prisma.SortOrder
  school?: Prisma.SchoolOrderByWithRelationInput
  discipline?: Prisma.DisciplineOrderByWithRelationInput
}

export type SchoolDisciplineWhereUniqueInput = Prisma.AtLeast<{
  schoolId_disciplineId?: Prisma.SchoolDisciplineSchoolIdDisciplineIdCompoundUniqueInput
  AND?: Prisma.SchoolDisciplineWhereInput | Prisma.SchoolDisciplineWhereInput[]
  OR?: Prisma.SchoolDisciplineWhereInput[]
  NOT?: Prisma.SchoolDisciplineWhereInput | Prisma.SchoolDisciplineWhereInput[]
  schoolId?: Prisma.StringFilter<"SchoolDiscipline"> | string
  disciplineId?: Prisma.StringFilter<"SchoolDiscipline"> | string
  school?: Prisma.XOR<Prisma.SchoolScalarRelationFilter, Prisma.SchoolWhereInput>
  discipline?: Prisma.XOR<Prisma.DisciplineScalarRelationFilter, Prisma.DisciplineWhereInput>
}, "schoolId_disciplineId">

export type SchoolDisciplineOrderByWithAggregationInput = {
  schoolId?: Prisma.SortOrder
  disciplineId?: Prisma.SortOrder
  _count?: Prisma.SchoolDisciplineCountOrderByAggregateInput
  _max?: Prisma.SchoolDisciplineMaxOrderByAggregateInput
  _min?: Prisma.SchoolDisciplineMinOrderByAggregateInput
}

export type SchoolDisciplineScalarWhereWithAggregatesInput = {
  AND?: Prisma.SchoolDisciplineScalarWhereWithAggregatesInput | Prisma.SchoolDisciplineScalarWhereWithAggregatesInput[]
  OR?: Prisma.SchoolDisciplineScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SchoolDisciplineScalarWhereWithAggregatesInput | Prisma.SchoolDisciplineScalarWhereWithAggregatesInput[]
  schoolId?: Prisma.StringWithAggregatesFilter<"SchoolDiscipline"> | string
  disciplineId?: Prisma.StringWithAggregatesFilter<"SchoolDiscipline"> | string
}

export type SchoolDisciplineCreateInput = {
  school: Prisma.SchoolCreateNestedOneWithoutDisciplinesInput
  discipline: Prisma.DisciplineCreateNestedOneWithoutSchoolsInput
}

export type SchoolDisciplineUncheckedCreateInput = {
  schoolId: string
  disciplineId: string
}

export type SchoolDisciplineUpdateInput = {
  school?: Prisma.SchoolUpdateOneRequiredWithoutDisciplinesNestedInput
  discipline?: Prisma.DisciplineUpdateOneRequiredWithoutSchoolsNestedInput
}

export type SchoolDisciplineUncheckedUpdateInput = {
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  disciplineId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SchoolDisciplineCreateManyInput = {
  schoolId: string
  disciplineId: string
}

export type SchoolDisciplineUpdateManyMutationInput = {

}

export type SchoolDisciplineUncheckedUpdateManyInput = {
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  disciplineId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SchoolDisciplineListRelationFilter = {
  every?: Prisma.SchoolDisciplineWhereInput
  some?: Prisma.SchoolDisciplineWhereInput
  none?: Prisma.SchoolDisciplineWhereInput
}

export type SchoolDisciplineOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SchoolDisciplineSchoolIdDisciplineIdCompoundUniqueInput = {
  schoolId: string
  disciplineId: string
}

export type SchoolDisciplineCountOrderByAggregateInput = {
  schoolId?: Prisma.SortOrder
  disciplineId?: Prisma.SortOrder
}

export type SchoolDisciplineMaxOrderByAggregateInput = {
  schoolId?: Prisma.SortOrder
  disciplineId?: Prisma.SortOrder
}

export type SchoolDisciplineMinOrderByAggregateInput = {
  schoolId?: Prisma.SortOrder
  disciplineId?: Prisma.SortOrder
}

export type SchoolDisciplineCreateNestedManyWithoutDisciplineInput = {
  create?: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutDisciplineInput, Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput> | Prisma.SchoolDisciplineCreateWithoutDisciplineInput[] | Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput[]
  connectOrCreate?: Prisma.SchoolDisciplineCreateOrConnectWithoutDisciplineInput | Prisma.SchoolDisciplineCreateOrConnectWithoutDisciplineInput[]
  createMany?: Prisma.SchoolDisciplineCreateManyDisciplineInputEnvelope
  connect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
}

export type SchoolDisciplineUncheckedCreateNestedManyWithoutDisciplineInput = {
  create?: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutDisciplineInput, Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput> | Prisma.SchoolDisciplineCreateWithoutDisciplineInput[] | Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput[]
  connectOrCreate?: Prisma.SchoolDisciplineCreateOrConnectWithoutDisciplineInput | Prisma.SchoolDisciplineCreateOrConnectWithoutDisciplineInput[]
  createMany?: Prisma.SchoolDisciplineCreateManyDisciplineInputEnvelope
  connect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
}

export type SchoolDisciplineUpdateManyWithoutDisciplineNestedInput = {
  create?: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutDisciplineInput, Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput> | Prisma.SchoolDisciplineCreateWithoutDisciplineInput[] | Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput[]
  connectOrCreate?: Prisma.SchoolDisciplineCreateOrConnectWithoutDisciplineInput | Prisma.SchoolDisciplineCreateOrConnectWithoutDisciplineInput[]
  upsert?: Prisma.SchoolDisciplineUpsertWithWhereUniqueWithoutDisciplineInput | Prisma.SchoolDisciplineUpsertWithWhereUniqueWithoutDisciplineInput[]
  createMany?: Prisma.SchoolDisciplineCreateManyDisciplineInputEnvelope
  set?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  disconnect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  delete?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  connect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  update?: Prisma.SchoolDisciplineUpdateWithWhereUniqueWithoutDisciplineInput | Prisma.SchoolDisciplineUpdateWithWhereUniqueWithoutDisciplineInput[]
  updateMany?: Prisma.SchoolDisciplineUpdateManyWithWhereWithoutDisciplineInput | Prisma.SchoolDisciplineUpdateManyWithWhereWithoutDisciplineInput[]
  deleteMany?: Prisma.SchoolDisciplineScalarWhereInput | Prisma.SchoolDisciplineScalarWhereInput[]
}

export type SchoolDisciplineUncheckedUpdateManyWithoutDisciplineNestedInput = {
  create?: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutDisciplineInput, Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput> | Prisma.SchoolDisciplineCreateWithoutDisciplineInput[] | Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput[]
  connectOrCreate?: Prisma.SchoolDisciplineCreateOrConnectWithoutDisciplineInput | Prisma.SchoolDisciplineCreateOrConnectWithoutDisciplineInput[]
  upsert?: Prisma.SchoolDisciplineUpsertWithWhereUniqueWithoutDisciplineInput | Prisma.SchoolDisciplineUpsertWithWhereUniqueWithoutDisciplineInput[]
  createMany?: Prisma.SchoolDisciplineCreateManyDisciplineInputEnvelope
  set?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  disconnect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  delete?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  connect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  update?: Prisma.SchoolDisciplineUpdateWithWhereUniqueWithoutDisciplineInput | Prisma.SchoolDisciplineUpdateWithWhereUniqueWithoutDisciplineInput[]
  updateMany?: Prisma.SchoolDisciplineUpdateManyWithWhereWithoutDisciplineInput | Prisma.SchoolDisciplineUpdateManyWithWhereWithoutDisciplineInput[]
  deleteMany?: Prisma.SchoolDisciplineScalarWhereInput | Prisma.SchoolDisciplineScalarWhereInput[]
}

export type SchoolDisciplineCreateNestedManyWithoutSchoolInput = {
  create?: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutSchoolInput, Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput> | Prisma.SchoolDisciplineCreateWithoutSchoolInput[] | Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.SchoolDisciplineCreateOrConnectWithoutSchoolInput | Prisma.SchoolDisciplineCreateOrConnectWithoutSchoolInput[]
  createMany?: Prisma.SchoolDisciplineCreateManySchoolInputEnvelope
  connect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
}

export type SchoolDisciplineUncheckedCreateNestedManyWithoutSchoolInput = {
  create?: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutSchoolInput, Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput> | Prisma.SchoolDisciplineCreateWithoutSchoolInput[] | Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.SchoolDisciplineCreateOrConnectWithoutSchoolInput | Prisma.SchoolDisciplineCreateOrConnectWithoutSchoolInput[]
  createMany?: Prisma.SchoolDisciplineCreateManySchoolInputEnvelope
  connect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
}

export type SchoolDisciplineUpdateManyWithoutSchoolNestedInput = {
  create?: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutSchoolInput, Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput> | Prisma.SchoolDisciplineCreateWithoutSchoolInput[] | Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.SchoolDisciplineCreateOrConnectWithoutSchoolInput | Prisma.SchoolDisciplineCreateOrConnectWithoutSchoolInput[]
  upsert?: Prisma.SchoolDisciplineUpsertWithWhereUniqueWithoutSchoolInput | Prisma.SchoolDisciplineUpsertWithWhereUniqueWithoutSchoolInput[]
  createMany?: Prisma.SchoolDisciplineCreateManySchoolInputEnvelope
  set?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  disconnect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  delete?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  connect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  update?: Prisma.SchoolDisciplineUpdateWithWhereUniqueWithoutSchoolInput | Prisma.SchoolDisciplineUpdateWithWhereUniqueWithoutSchoolInput[]
  updateMany?: Prisma.SchoolDisciplineUpdateManyWithWhereWithoutSchoolInput | Prisma.SchoolDisciplineUpdateManyWithWhereWithoutSchoolInput[]
  deleteMany?: Prisma.SchoolDisciplineScalarWhereInput | Prisma.SchoolDisciplineScalarWhereInput[]
}

export type SchoolDisciplineUncheckedUpdateManyWithoutSchoolNestedInput = {
  create?: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutSchoolInput, Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput> | Prisma.SchoolDisciplineCreateWithoutSchoolInput[] | Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.SchoolDisciplineCreateOrConnectWithoutSchoolInput | Prisma.SchoolDisciplineCreateOrConnectWithoutSchoolInput[]
  upsert?: Prisma.SchoolDisciplineUpsertWithWhereUniqueWithoutSchoolInput | Prisma.SchoolDisciplineUpsertWithWhereUniqueWithoutSchoolInput[]
  createMany?: Prisma.SchoolDisciplineCreateManySchoolInputEnvelope
  set?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  disconnect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  delete?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  connect?: Prisma.SchoolDisciplineWhereUniqueInput | Prisma.SchoolDisciplineWhereUniqueInput[]
  update?: Prisma.SchoolDisciplineUpdateWithWhereUniqueWithoutSchoolInput | Prisma.SchoolDisciplineUpdateWithWhereUniqueWithoutSchoolInput[]
  updateMany?: Prisma.SchoolDisciplineUpdateManyWithWhereWithoutSchoolInput | Prisma.SchoolDisciplineUpdateManyWithWhereWithoutSchoolInput[]
  deleteMany?: Prisma.SchoolDisciplineScalarWhereInput | Prisma.SchoolDisciplineScalarWhereInput[]
}

export type SchoolDisciplineCreateWithoutDisciplineInput = {
  school: Prisma.SchoolCreateNestedOneWithoutDisciplinesInput
}

export type SchoolDisciplineUncheckedCreateWithoutDisciplineInput = {
  schoolId: string
}

export type SchoolDisciplineCreateOrConnectWithoutDisciplineInput = {
  where: Prisma.SchoolDisciplineWhereUniqueInput
  create: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutDisciplineInput, Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput>
}

export type SchoolDisciplineCreateManyDisciplineInputEnvelope = {
  data: Prisma.SchoolDisciplineCreateManyDisciplineInput | Prisma.SchoolDisciplineCreateManyDisciplineInput[]
  skipDuplicates?: boolean
}

export type SchoolDisciplineUpsertWithWhereUniqueWithoutDisciplineInput = {
  where: Prisma.SchoolDisciplineWhereUniqueInput
  update: Prisma.XOR<Prisma.SchoolDisciplineUpdateWithoutDisciplineInput, Prisma.SchoolDisciplineUncheckedUpdateWithoutDisciplineInput>
  create: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutDisciplineInput, Prisma.SchoolDisciplineUncheckedCreateWithoutDisciplineInput>
}

export type SchoolDisciplineUpdateWithWhereUniqueWithoutDisciplineInput = {
  where: Prisma.SchoolDisciplineWhereUniqueInput
  data: Prisma.XOR<Prisma.SchoolDisciplineUpdateWithoutDisciplineInput, Prisma.SchoolDisciplineUncheckedUpdateWithoutDisciplineInput>
}

export type SchoolDisciplineUpdateManyWithWhereWithoutDisciplineInput = {
  where: Prisma.SchoolDisciplineScalarWhereInput
  data: Prisma.XOR<Prisma.SchoolDisciplineUpdateManyMutationInput, Prisma.SchoolDisciplineUncheckedUpdateManyWithoutDisciplineInput>
}

export type SchoolDisciplineScalarWhereInput = {
  AND?: Prisma.SchoolDisciplineScalarWhereInput | Prisma.SchoolDisciplineScalarWhereInput[]
  OR?: Prisma.SchoolDisciplineScalarWhereInput[]
  NOT?: Prisma.SchoolDisciplineScalarWhereInput | Prisma.SchoolDisciplineScalarWhereInput[]
  schoolId?: Prisma.StringFilter<"SchoolDiscipline"> | string
  disciplineId?: Prisma.StringFilter<"SchoolDiscipline"> | string
}

export type SchoolDisciplineCreateWithoutSchoolInput = {
  discipline: Prisma.DisciplineCreateNestedOneWithoutSchoolsInput
}

export type SchoolDisciplineUncheckedCreateWithoutSchoolInput = {
  disciplineId: string
}

export type SchoolDisciplineCreateOrConnectWithoutSchoolInput = {
  where: Prisma.SchoolDisciplineWhereUniqueInput
  create: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutSchoolInput, Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput>
}

export type SchoolDisciplineCreateManySchoolInputEnvelope = {
  data: Prisma.SchoolDisciplineCreateManySchoolInput | Prisma.SchoolDisciplineCreateManySchoolInput[]
  skipDuplicates?: boolean
}

export type SchoolDisciplineUpsertWithWhereUniqueWithoutSchoolInput = {
  where: Prisma.SchoolDisciplineWhereUniqueInput
  update: Prisma.XOR<Prisma.SchoolDisciplineUpdateWithoutSchoolInput, Prisma.SchoolDisciplineUncheckedUpdateWithoutSchoolInput>
  create: Prisma.XOR<Prisma.SchoolDisciplineCreateWithoutSchoolInput, Prisma.SchoolDisciplineUncheckedCreateWithoutSchoolInput>
}

export type SchoolDisciplineUpdateWithWhereUniqueWithoutSchoolInput = {
  where: Prisma.SchoolDisciplineWhereUniqueInput
  data: Prisma.XOR<Prisma.SchoolDisciplineUpdateWithoutSchoolInput, Prisma.SchoolDisciplineUncheckedUpdateWithoutSchoolInput>
}

export type SchoolDisciplineUpdateManyWithWhereWithoutSchoolInput = {
  where: Prisma.SchoolDisciplineScalarWhereInput
  data: Prisma.XOR<Prisma.SchoolDisciplineUpdateManyMutationInput, Prisma.SchoolDisciplineUncheckedUpdateManyWithoutSchoolInput>
}

export type SchoolDisciplineCreateManyDisciplineInput = {
  schoolId: string
}

export type SchoolDisciplineUpdateWithoutDisciplineInput = {
  school?: Prisma.SchoolUpdateOneRequiredWithoutDisciplinesNestedInput
}

export type SchoolDisciplineUncheckedUpdateWithoutDisciplineInput = {
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SchoolDisciplineUncheckedUpdateManyWithoutDisciplineInput = {
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SchoolDisciplineCreateManySchoolInput = {
  disciplineId: string
}

export type SchoolDisciplineUpdateWithoutSchoolInput = {
  discipline?: Prisma.DisciplineUpdateOneRequiredWithoutSchoolsNestedInput
}

export type SchoolDisciplineUncheckedUpdateWithoutSchoolInput = {
  disciplineId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SchoolDisciplineUncheckedUpdateManyWithoutSchoolInput = {
  disciplineId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SchoolDisciplineSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  schoolId?: boolean
  disciplineId?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  discipline?: boolean | Prisma.DisciplineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schoolDiscipline"]>

export type SchoolDisciplineSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  schoolId?: boolean
  disciplineId?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  discipline?: boolean | Prisma.DisciplineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schoolDiscipline"]>

export type SchoolDisciplineSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  schoolId?: boolean
  disciplineId?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  discipline?: boolean | Prisma.DisciplineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schoolDiscipline"]>

export type SchoolDisciplineSelectScalar = {
  schoolId?: boolean
  disciplineId?: boolean
}

export type SchoolDisciplineOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"schoolId" | "disciplineId", ExtArgs["result"]["schoolDiscipline"]>
export type SchoolDisciplineInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  discipline?: boolean | Prisma.DisciplineDefaultArgs<ExtArgs>
}
export type SchoolDisciplineIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  discipline?: boolean | Prisma.DisciplineDefaultArgs<ExtArgs>
}
export type SchoolDisciplineIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  discipline?: boolean | Prisma.DisciplineDefaultArgs<ExtArgs>
}

export type $SchoolDisciplinePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SchoolDiscipline"
  objects: {
    school: Prisma.$SchoolPayload<ExtArgs>
    discipline: Prisma.$DisciplinePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    schoolId: string
    disciplineId: string
  }, ExtArgs["result"]["schoolDiscipline"]>
  composites: {}
}

export type SchoolDisciplineGetPayload<S extends boolean | null | undefined | SchoolDisciplineDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload, S>

export type SchoolDisciplineCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SchoolDisciplineFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SchoolDisciplineCountAggregateInputType | true
  }

export interface SchoolDisciplineDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SchoolDiscipline'], meta: { name: 'SchoolDiscipline' } }
  /**
   * Find zero or one SchoolDiscipline that matches the filter.
   * @param {SchoolDisciplineFindUniqueArgs} args - Arguments to find a SchoolDiscipline
   * @example
   * // Get one SchoolDiscipline
   * const schoolDiscipline = await prisma.schoolDiscipline.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SchoolDisciplineFindUniqueArgs>(args: Prisma.SelectSubset<T, SchoolDisciplineFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SchoolDisciplineClient<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SchoolDiscipline that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SchoolDisciplineFindUniqueOrThrowArgs} args - Arguments to find a SchoolDiscipline
   * @example
   * // Get one SchoolDiscipline
   * const schoolDiscipline = await prisma.schoolDiscipline.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SchoolDisciplineFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SchoolDisciplineFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SchoolDisciplineClient<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SchoolDiscipline that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolDisciplineFindFirstArgs} args - Arguments to find a SchoolDiscipline
   * @example
   * // Get one SchoolDiscipline
   * const schoolDiscipline = await prisma.schoolDiscipline.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SchoolDisciplineFindFirstArgs>(args?: Prisma.SelectSubset<T, SchoolDisciplineFindFirstArgs<ExtArgs>>): Prisma.Prisma__SchoolDisciplineClient<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SchoolDiscipline that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolDisciplineFindFirstOrThrowArgs} args - Arguments to find a SchoolDiscipline
   * @example
   * // Get one SchoolDiscipline
   * const schoolDiscipline = await prisma.schoolDiscipline.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SchoolDisciplineFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SchoolDisciplineFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SchoolDisciplineClient<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SchoolDisciplines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolDisciplineFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SchoolDisciplines
   * const schoolDisciplines = await prisma.schoolDiscipline.findMany()
   * 
   * // Get first 10 SchoolDisciplines
   * const schoolDisciplines = await prisma.schoolDiscipline.findMany({ take: 10 })
   * 
   * // Only select the `schoolId`
   * const schoolDisciplineWithSchoolIdOnly = await prisma.schoolDiscipline.findMany({ select: { schoolId: true } })
   * 
   */
  findMany<T extends SchoolDisciplineFindManyArgs>(args?: Prisma.SelectSubset<T, SchoolDisciplineFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SchoolDiscipline.
   * @param {SchoolDisciplineCreateArgs} args - Arguments to create a SchoolDiscipline.
   * @example
   * // Create one SchoolDiscipline
   * const SchoolDiscipline = await prisma.schoolDiscipline.create({
   *   data: {
   *     // ... data to create a SchoolDiscipline
   *   }
   * })
   * 
   */
  create<T extends SchoolDisciplineCreateArgs>(args: Prisma.SelectSubset<T, SchoolDisciplineCreateArgs<ExtArgs>>): Prisma.Prisma__SchoolDisciplineClient<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SchoolDisciplines.
   * @param {SchoolDisciplineCreateManyArgs} args - Arguments to create many SchoolDisciplines.
   * @example
   * // Create many SchoolDisciplines
   * const schoolDiscipline = await prisma.schoolDiscipline.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SchoolDisciplineCreateManyArgs>(args?: Prisma.SelectSubset<T, SchoolDisciplineCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SchoolDisciplines and returns the data saved in the database.
   * @param {SchoolDisciplineCreateManyAndReturnArgs} args - Arguments to create many SchoolDisciplines.
   * @example
   * // Create many SchoolDisciplines
   * const schoolDiscipline = await prisma.schoolDiscipline.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SchoolDisciplines and only return the `schoolId`
   * const schoolDisciplineWithSchoolIdOnly = await prisma.schoolDiscipline.createManyAndReturn({
   *   select: { schoolId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SchoolDisciplineCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SchoolDisciplineCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SchoolDiscipline.
   * @param {SchoolDisciplineDeleteArgs} args - Arguments to delete one SchoolDiscipline.
   * @example
   * // Delete one SchoolDiscipline
   * const SchoolDiscipline = await prisma.schoolDiscipline.delete({
   *   where: {
   *     // ... filter to delete one SchoolDiscipline
   *   }
   * })
   * 
   */
  delete<T extends SchoolDisciplineDeleteArgs>(args: Prisma.SelectSubset<T, SchoolDisciplineDeleteArgs<ExtArgs>>): Prisma.Prisma__SchoolDisciplineClient<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SchoolDiscipline.
   * @param {SchoolDisciplineUpdateArgs} args - Arguments to update one SchoolDiscipline.
   * @example
   * // Update one SchoolDiscipline
   * const schoolDiscipline = await prisma.schoolDiscipline.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SchoolDisciplineUpdateArgs>(args: Prisma.SelectSubset<T, SchoolDisciplineUpdateArgs<ExtArgs>>): Prisma.Prisma__SchoolDisciplineClient<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SchoolDisciplines.
   * @param {SchoolDisciplineDeleteManyArgs} args - Arguments to filter SchoolDisciplines to delete.
   * @example
   * // Delete a few SchoolDisciplines
   * const { count } = await prisma.schoolDiscipline.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SchoolDisciplineDeleteManyArgs>(args?: Prisma.SelectSubset<T, SchoolDisciplineDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SchoolDisciplines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolDisciplineUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SchoolDisciplines
   * const schoolDiscipline = await prisma.schoolDiscipline.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SchoolDisciplineUpdateManyArgs>(args: Prisma.SelectSubset<T, SchoolDisciplineUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SchoolDisciplines and returns the data updated in the database.
   * @param {SchoolDisciplineUpdateManyAndReturnArgs} args - Arguments to update many SchoolDisciplines.
   * @example
   * // Update many SchoolDisciplines
   * const schoolDiscipline = await prisma.schoolDiscipline.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SchoolDisciplines and only return the `schoolId`
   * const schoolDisciplineWithSchoolIdOnly = await prisma.schoolDiscipline.updateManyAndReturn({
   *   select: { schoolId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SchoolDisciplineUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SchoolDisciplineUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SchoolDiscipline.
   * @param {SchoolDisciplineUpsertArgs} args - Arguments to update or create a SchoolDiscipline.
   * @example
   * // Update or create a SchoolDiscipline
   * const schoolDiscipline = await prisma.schoolDiscipline.upsert({
   *   create: {
   *     // ... data to create a SchoolDiscipline
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SchoolDiscipline we want to update
   *   }
   * })
   */
  upsert<T extends SchoolDisciplineUpsertArgs>(args: Prisma.SelectSubset<T, SchoolDisciplineUpsertArgs<ExtArgs>>): Prisma.Prisma__SchoolDisciplineClient<runtime.Types.Result.GetResult<Prisma.$SchoolDisciplinePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SchoolDisciplines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolDisciplineCountArgs} args - Arguments to filter SchoolDisciplines to count.
   * @example
   * // Count the number of SchoolDisciplines
   * const count = await prisma.schoolDiscipline.count({
   *   where: {
   *     // ... the filter for the SchoolDisciplines we want to count
   *   }
   * })
  **/
  count<T extends SchoolDisciplineCountArgs>(
    args?: Prisma.Subset<T, SchoolDisciplineCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SchoolDisciplineCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SchoolDiscipline.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolDisciplineAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SchoolDisciplineAggregateArgs>(args: Prisma.Subset<T, SchoolDisciplineAggregateArgs>): Prisma.PrismaPromise<GetSchoolDisciplineAggregateType<T>>

  /**
   * Group by SchoolDiscipline.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SchoolDisciplineGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SchoolDisciplineGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SchoolDisciplineGroupByArgs['orderBy'] }
      : { orderBy?: SchoolDisciplineGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SchoolDisciplineGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSchoolDisciplineGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SchoolDiscipline model
 */
readonly fields: SchoolDisciplineFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SchoolDiscipline.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SchoolDisciplineClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  school<T extends Prisma.SchoolDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SchoolDefaultArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  discipline<T extends Prisma.DisciplineDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DisciplineDefaultArgs<ExtArgs>>): Prisma.Prisma__DisciplineClient<runtime.Types.Result.GetResult<Prisma.$DisciplinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SchoolDiscipline model
 */
export interface SchoolDisciplineFieldRefs {
  readonly schoolId: Prisma.FieldRef<"SchoolDiscipline", 'String'>
  readonly disciplineId: Prisma.FieldRef<"SchoolDiscipline", 'String'>
}
    

// Custom InputTypes
/**
 * SchoolDiscipline findUnique
 */
export type SchoolDisciplineFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * Filter, which SchoolDiscipline to fetch.
   */
  where: Prisma.SchoolDisciplineWhereUniqueInput
}

/**
 * SchoolDiscipline findUniqueOrThrow
 */
export type SchoolDisciplineFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * Filter, which SchoolDiscipline to fetch.
   */
  where: Prisma.SchoolDisciplineWhereUniqueInput
}

/**
 * SchoolDiscipline findFirst
 */
export type SchoolDisciplineFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * Filter, which SchoolDiscipline to fetch.
   */
  where?: Prisma.SchoolDisciplineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SchoolDisciplines to fetch.
   */
  orderBy?: Prisma.SchoolDisciplineOrderByWithRelationInput | Prisma.SchoolDisciplineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SchoolDisciplines.
   */
  cursor?: Prisma.SchoolDisciplineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SchoolDisciplines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SchoolDisciplines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SchoolDisciplines.
   */
  distinct?: Prisma.SchoolDisciplineScalarFieldEnum | Prisma.SchoolDisciplineScalarFieldEnum[]
}

/**
 * SchoolDiscipline findFirstOrThrow
 */
export type SchoolDisciplineFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * Filter, which SchoolDiscipline to fetch.
   */
  where?: Prisma.SchoolDisciplineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SchoolDisciplines to fetch.
   */
  orderBy?: Prisma.SchoolDisciplineOrderByWithRelationInput | Prisma.SchoolDisciplineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SchoolDisciplines.
   */
  cursor?: Prisma.SchoolDisciplineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SchoolDisciplines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SchoolDisciplines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SchoolDisciplines.
   */
  distinct?: Prisma.SchoolDisciplineScalarFieldEnum | Prisma.SchoolDisciplineScalarFieldEnum[]
}

/**
 * SchoolDiscipline findMany
 */
export type SchoolDisciplineFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * Filter, which SchoolDisciplines to fetch.
   */
  where?: Prisma.SchoolDisciplineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SchoolDisciplines to fetch.
   */
  orderBy?: Prisma.SchoolDisciplineOrderByWithRelationInput | Prisma.SchoolDisciplineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SchoolDisciplines.
   */
  cursor?: Prisma.SchoolDisciplineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SchoolDisciplines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SchoolDisciplines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SchoolDisciplines.
   */
  distinct?: Prisma.SchoolDisciplineScalarFieldEnum | Prisma.SchoolDisciplineScalarFieldEnum[]
}

/**
 * SchoolDiscipline create
 */
export type SchoolDisciplineCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * The data needed to create a SchoolDiscipline.
   */
  data: Prisma.XOR<Prisma.SchoolDisciplineCreateInput, Prisma.SchoolDisciplineUncheckedCreateInput>
}

/**
 * SchoolDiscipline createMany
 */
export type SchoolDisciplineCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SchoolDisciplines.
   */
  data: Prisma.SchoolDisciplineCreateManyInput | Prisma.SchoolDisciplineCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SchoolDiscipline createManyAndReturn
 */
export type SchoolDisciplineCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * The data used to create many SchoolDisciplines.
   */
  data: Prisma.SchoolDisciplineCreateManyInput | Prisma.SchoolDisciplineCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SchoolDiscipline update
 */
export type SchoolDisciplineUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * The data needed to update a SchoolDiscipline.
   */
  data: Prisma.XOR<Prisma.SchoolDisciplineUpdateInput, Prisma.SchoolDisciplineUncheckedUpdateInput>
  /**
   * Choose, which SchoolDiscipline to update.
   */
  where: Prisma.SchoolDisciplineWhereUniqueInput
}

/**
 * SchoolDiscipline updateMany
 */
export type SchoolDisciplineUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SchoolDisciplines.
   */
  data: Prisma.XOR<Prisma.SchoolDisciplineUpdateManyMutationInput, Prisma.SchoolDisciplineUncheckedUpdateManyInput>
  /**
   * Filter which SchoolDisciplines to update
   */
  where?: Prisma.SchoolDisciplineWhereInput
  /**
   * Limit how many SchoolDisciplines to update.
   */
  limit?: number
}

/**
 * SchoolDiscipline updateManyAndReturn
 */
export type SchoolDisciplineUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * The data used to update SchoolDisciplines.
   */
  data: Prisma.XOR<Prisma.SchoolDisciplineUpdateManyMutationInput, Prisma.SchoolDisciplineUncheckedUpdateManyInput>
  /**
   * Filter which SchoolDisciplines to update
   */
  where?: Prisma.SchoolDisciplineWhereInput
  /**
   * Limit how many SchoolDisciplines to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SchoolDiscipline upsert
 */
export type SchoolDisciplineUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * The filter to search for the SchoolDiscipline to update in case it exists.
   */
  where: Prisma.SchoolDisciplineWhereUniqueInput
  /**
   * In case the SchoolDiscipline found by the `where` argument doesn't exist, create a new SchoolDiscipline with this data.
   */
  create: Prisma.XOR<Prisma.SchoolDisciplineCreateInput, Prisma.SchoolDisciplineUncheckedCreateInput>
  /**
   * In case the SchoolDiscipline was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SchoolDisciplineUpdateInput, Prisma.SchoolDisciplineUncheckedUpdateInput>
}

/**
 * SchoolDiscipline delete
 */
export type SchoolDisciplineDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
  /**
   * Filter which SchoolDiscipline to delete.
   */
  where: Prisma.SchoolDisciplineWhereUniqueInput
}

/**
 * SchoolDiscipline deleteMany
 */
export type SchoolDisciplineDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SchoolDisciplines to delete
   */
  where?: Prisma.SchoolDisciplineWhereInput
  /**
   * Limit how many SchoolDisciplines to delete.
   */
  limit?: number
}

/**
 * SchoolDiscipline without action
 */
export type SchoolDisciplineDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SchoolDiscipline
   */
  select?: Prisma.SchoolDisciplineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SchoolDiscipline
   */
  omit?: Prisma.SchoolDisciplineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SchoolDisciplineInclude<ExtArgs> | null
}
