
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Waiver` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Waiver
 * 
 */
export type WaiverModel = runtime.Types.Result.DefaultSelection<Prisma.$WaiverPayload>

export type AggregateWaiver = {
  _count: WaiverCountAggregateOutputType | null
  _min: WaiverMinAggregateOutputType | null
  _max: WaiverMaxAggregateOutputType | null
}

export type WaiverMinAggregateOutputType = {
  id: string | null
  schoolId: string | null
  title: string | null
  content: string | null
  version: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WaiverMaxAggregateOutputType = {
  id: string | null
  schoolId: string | null
  title: string | null
  content: string | null
  version: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WaiverCountAggregateOutputType = {
  id: number
  schoolId: number
  title: number
  content: number
  version: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type WaiverMinAggregateInputType = {
  id?: true
  schoolId?: true
  title?: true
  content?: true
  version?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type WaiverMaxAggregateInputType = {
  id?: true
  schoolId?: true
  title?: true
  content?: true
  version?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type WaiverCountAggregateInputType = {
  id?: true
  schoolId?: true
  title?: true
  content?: true
  version?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WaiverAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Waiver to aggregate.
   */
  where?: Prisma.WaiverWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Waivers to fetch.
   */
  orderBy?: Prisma.WaiverOrderByWithRelationInput | Prisma.WaiverOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WaiverWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Waivers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Waivers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Waivers
  **/
  _count?: true | WaiverCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WaiverMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WaiverMaxAggregateInputType
}

export type GetWaiverAggregateType<T extends WaiverAggregateArgs> = {
      [P in keyof T & keyof AggregateWaiver]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWaiver[P]>
    : Prisma.GetScalarType<T[P], AggregateWaiver[P]>
}




export type WaiverGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WaiverWhereInput
  orderBy?: Prisma.WaiverOrderByWithAggregationInput | Prisma.WaiverOrderByWithAggregationInput[]
  by: Prisma.WaiverScalarFieldEnum[] | Prisma.WaiverScalarFieldEnum
  having?: Prisma.WaiverScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WaiverCountAggregateInputType | true
  _min?: WaiverMinAggregateInputType
  _max?: WaiverMaxAggregateInputType
}

export type WaiverGroupByOutputType = {
  id: string
  schoolId: string
  title: string
  content: string
  version: string
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: WaiverCountAggregateOutputType | null
  _min: WaiverMinAggregateOutputType | null
  _max: WaiverMaxAggregateOutputType | null
}

export type GetWaiverGroupByPayload<T extends WaiverGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WaiverGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WaiverGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WaiverGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WaiverGroupByOutputType[P]>
      }
    >
  >



export type WaiverWhereInput = {
  AND?: Prisma.WaiverWhereInput | Prisma.WaiverWhereInput[]
  OR?: Prisma.WaiverWhereInput[]
  NOT?: Prisma.WaiverWhereInput | Prisma.WaiverWhereInput[]
  id?: Prisma.StringFilter<"Waiver"> | string
  schoolId?: Prisma.StringFilter<"Waiver"> | string
  title?: Prisma.StringFilter<"Waiver"> | string
  content?: Prisma.StringFilter<"Waiver"> | string
  version?: Prisma.StringFilter<"Waiver"> | string
  isActive?: Prisma.BoolFilter<"Waiver"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Waiver"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Waiver"> | Date | string
  school?: Prisma.XOR<Prisma.SchoolScalarRelationFilter, Prisma.SchoolWhereInput>
  signedBy?: Prisma.UserWaiverListRelationFilter
}

export type WaiverOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  school?: Prisma.SchoolOrderByWithRelationInput
  signedBy?: Prisma.UserWaiverOrderByRelationAggregateInput
}

export type WaiverWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WaiverWhereInput | Prisma.WaiverWhereInput[]
  OR?: Prisma.WaiverWhereInput[]
  NOT?: Prisma.WaiverWhereInput | Prisma.WaiverWhereInput[]
  schoolId?: Prisma.StringFilter<"Waiver"> | string
  title?: Prisma.StringFilter<"Waiver"> | string
  content?: Prisma.StringFilter<"Waiver"> | string
  version?: Prisma.StringFilter<"Waiver"> | string
  isActive?: Prisma.BoolFilter<"Waiver"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Waiver"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Waiver"> | Date | string
  school?: Prisma.XOR<Prisma.SchoolScalarRelationFilter, Prisma.SchoolWhereInput>
  signedBy?: Prisma.UserWaiverListRelationFilter
}, "id">

export type WaiverOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.WaiverCountOrderByAggregateInput
  _max?: Prisma.WaiverMaxOrderByAggregateInput
  _min?: Prisma.WaiverMinOrderByAggregateInput
}

export type WaiverScalarWhereWithAggregatesInput = {
  AND?: Prisma.WaiverScalarWhereWithAggregatesInput | Prisma.WaiverScalarWhereWithAggregatesInput[]
  OR?: Prisma.WaiverScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WaiverScalarWhereWithAggregatesInput | Prisma.WaiverScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Waiver"> | string
  schoolId?: Prisma.StringWithAggregatesFilter<"Waiver"> | string
  title?: Prisma.StringWithAggregatesFilter<"Waiver"> | string
  content?: Prisma.StringWithAggregatesFilter<"Waiver"> | string
  version?: Prisma.StringWithAggregatesFilter<"Waiver"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"Waiver"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Waiver"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Waiver"> | Date | string
}

export type WaiverCreateInput = {
  id?: string
  title: string
  content: string
  version?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  school: Prisma.SchoolCreateNestedOneWithoutWaiversInput
  signedBy?: Prisma.UserWaiverCreateNestedManyWithoutWaiverInput
}

export type WaiverUncheckedCreateInput = {
  id?: string
  schoolId: string
  title: string
  content: string
  version?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  signedBy?: Prisma.UserWaiverUncheckedCreateNestedManyWithoutWaiverInput
}

export type WaiverUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  school?: Prisma.SchoolUpdateOneRequiredWithoutWaiversNestedInput
  signedBy?: Prisma.UserWaiverUpdateManyWithoutWaiverNestedInput
}

export type WaiverUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  signedBy?: Prisma.UserWaiverUncheckedUpdateManyWithoutWaiverNestedInput
}

export type WaiverCreateManyInput = {
  id?: string
  schoolId: string
  title: string
  content: string
  version?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WaiverUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WaiverUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WaiverListRelationFilter = {
  every?: Prisma.WaiverWhereInput
  some?: Prisma.WaiverWhereInput
  none?: Prisma.WaiverWhereInput
}

export type WaiverOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WaiverCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WaiverMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WaiverMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  schoolId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WaiverScalarRelationFilter = {
  is?: Prisma.WaiverWhereInput
  isNot?: Prisma.WaiverWhereInput
}

export type WaiverCreateNestedManyWithoutSchoolInput = {
  create?: Prisma.XOR<Prisma.WaiverCreateWithoutSchoolInput, Prisma.WaiverUncheckedCreateWithoutSchoolInput> | Prisma.WaiverCreateWithoutSchoolInput[] | Prisma.WaiverUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.WaiverCreateOrConnectWithoutSchoolInput | Prisma.WaiverCreateOrConnectWithoutSchoolInput[]
  createMany?: Prisma.WaiverCreateManySchoolInputEnvelope
  connect?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
}

export type WaiverUncheckedCreateNestedManyWithoutSchoolInput = {
  create?: Prisma.XOR<Prisma.WaiverCreateWithoutSchoolInput, Prisma.WaiverUncheckedCreateWithoutSchoolInput> | Prisma.WaiverCreateWithoutSchoolInput[] | Prisma.WaiverUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.WaiverCreateOrConnectWithoutSchoolInput | Prisma.WaiverCreateOrConnectWithoutSchoolInput[]
  createMany?: Prisma.WaiverCreateManySchoolInputEnvelope
  connect?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
}

export type WaiverUpdateManyWithoutSchoolNestedInput = {
  create?: Prisma.XOR<Prisma.WaiverCreateWithoutSchoolInput, Prisma.WaiverUncheckedCreateWithoutSchoolInput> | Prisma.WaiverCreateWithoutSchoolInput[] | Prisma.WaiverUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.WaiverCreateOrConnectWithoutSchoolInput | Prisma.WaiverCreateOrConnectWithoutSchoolInput[]
  upsert?: Prisma.WaiverUpsertWithWhereUniqueWithoutSchoolInput | Prisma.WaiverUpsertWithWhereUniqueWithoutSchoolInput[]
  createMany?: Prisma.WaiverCreateManySchoolInputEnvelope
  set?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
  disconnect?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
  delete?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
  connect?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
  update?: Prisma.WaiverUpdateWithWhereUniqueWithoutSchoolInput | Prisma.WaiverUpdateWithWhereUniqueWithoutSchoolInput[]
  updateMany?: Prisma.WaiverUpdateManyWithWhereWithoutSchoolInput | Prisma.WaiverUpdateManyWithWhereWithoutSchoolInput[]
  deleteMany?: Prisma.WaiverScalarWhereInput | Prisma.WaiverScalarWhereInput[]
}

export type WaiverUncheckedUpdateManyWithoutSchoolNestedInput = {
  create?: Prisma.XOR<Prisma.WaiverCreateWithoutSchoolInput, Prisma.WaiverUncheckedCreateWithoutSchoolInput> | Prisma.WaiverCreateWithoutSchoolInput[] | Prisma.WaiverUncheckedCreateWithoutSchoolInput[]
  connectOrCreate?: Prisma.WaiverCreateOrConnectWithoutSchoolInput | Prisma.WaiverCreateOrConnectWithoutSchoolInput[]
  upsert?: Prisma.WaiverUpsertWithWhereUniqueWithoutSchoolInput | Prisma.WaiverUpsertWithWhereUniqueWithoutSchoolInput[]
  createMany?: Prisma.WaiverCreateManySchoolInputEnvelope
  set?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
  disconnect?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
  delete?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
  connect?: Prisma.WaiverWhereUniqueInput | Prisma.WaiverWhereUniqueInput[]
  update?: Prisma.WaiverUpdateWithWhereUniqueWithoutSchoolInput | Prisma.WaiverUpdateWithWhereUniqueWithoutSchoolInput[]
  updateMany?: Prisma.WaiverUpdateManyWithWhereWithoutSchoolInput | Prisma.WaiverUpdateManyWithWhereWithoutSchoolInput[]
  deleteMany?: Prisma.WaiverScalarWhereInput | Prisma.WaiverScalarWhereInput[]
}

export type WaiverCreateNestedOneWithoutSignedByInput = {
  create?: Prisma.XOR<Prisma.WaiverCreateWithoutSignedByInput, Prisma.WaiverUncheckedCreateWithoutSignedByInput>
  connectOrCreate?: Prisma.WaiverCreateOrConnectWithoutSignedByInput
  connect?: Prisma.WaiverWhereUniqueInput
}

export type WaiverUpdateOneRequiredWithoutSignedByNestedInput = {
  create?: Prisma.XOR<Prisma.WaiverCreateWithoutSignedByInput, Prisma.WaiverUncheckedCreateWithoutSignedByInput>
  connectOrCreate?: Prisma.WaiverCreateOrConnectWithoutSignedByInput
  upsert?: Prisma.WaiverUpsertWithoutSignedByInput
  connect?: Prisma.WaiverWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WaiverUpdateToOneWithWhereWithoutSignedByInput, Prisma.WaiverUpdateWithoutSignedByInput>, Prisma.WaiverUncheckedUpdateWithoutSignedByInput>
}

export type WaiverCreateWithoutSchoolInput = {
  id?: string
  title: string
  content: string
  version?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  signedBy?: Prisma.UserWaiverCreateNestedManyWithoutWaiverInput
}

export type WaiverUncheckedCreateWithoutSchoolInput = {
  id?: string
  title: string
  content: string
  version?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  signedBy?: Prisma.UserWaiverUncheckedCreateNestedManyWithoutWaiverInput
}

export type WaiverCreateOrConnectWithoutSchoolInput = {
  where: Prisma.WaiverWhereUniqueInput
  create: Prisma.XOR<Prisma.WaiverCreateWithoutSchoolInput, Prisma.WaiverUncheckedCreateWithoutSchoolInput>
}

export type WaiverCreateManySchoolInputEnvelope = {
  data: Prisma.WaiverCreateManySchoolInput | Prisma.WaiverCreateManySchoolInput[]
  skipDuplicates?: boolean
}

export type WaiverUpsertWithWhereUniqueWithoutSchoolInput = {
  where: Prisma.WaiverWhereUniqueInput
  update: Prisma.XOR<Prisma.WaiverUpdateWithoutSchoolInput, Prisma.WaiverUncheckedUpdateWithoutSchoolInput>
  create: Prisma.XOR<Prisma.WaiverCreateWithoutSchoolInput, Prisma.WaiverUncheckedCreateWithoutSchoolInput>
}

export type WaiverUpdateWithWhereUniqueWithoutSchoolInput = {
  where: Prisma.WaiverWhereUniqueInput
  data: Prisma.XOR<Prisma.WaiverUpdateWithoutSchoolInput, Prisma.WaiverUncheckedUpdateWithoutSchoolInput>
}

export type WaiverUpdateManyWithWhereWithoutSchoolInput = {
  where: Prisma.WaiverScalarWhereInput
  data: Prisma.XOR<Prisma.WaiverUpdateManyMutationInput, Prisma.WaiverUncheckedUpdateManyWithoutSchoolInput>
}

export type WaiverScalarWhereInput = {
  AND?: Prisma.WaiverScalarWhereInput | Prisma.WaiverScalarWhereInput[]
  OR?: Prisma.WaiverScalarWhereInput[]
  NOT?: Prisma.WaiverScalarWhereInput | Prisma.WaiverScalarWhereInput[]
  id?: Prisma.StringFilter<"Waiver"> | string
  schoolId?: Prisma.StringFilter<"Waiver"> | string
  title?: Prisma.StringFilter<"Waiver"> | string
  content?: Prisma.StringFilter<"Waiver"> | string
  version?: Prisma.StringFilter<"Waiver"> | string
  isActive?: Prisma.BoolFilter<"Waiver"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Waiver"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Waiver"> | Date | string
}

export type WaiverCreateWithoutSignedByInput = {
  id?: string
  title: string
  content: string
  version?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  school: Prisma.SchoolCreateNestedOneWithoutWaiversInput
}

export type WaiverUncheckedCreateWithoutSignedByInput = {
  id?: string
  schoolId: string
  title: string
  content: string
  version?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WaiverCreateOrConnectWithoutSignedByInput = {
  where: Prisma.WaiverWhereUniqueInput
  create: Prisma.XOR<Prisma.WaiverCreateWithoutSignedByInput, Prisma.WaiverUncheckedCreateWithoutSignedByInput>
}

export type WaiverUpsertWithoutSignedByInput = {
  update: Prisma.XOR<Prisma.WaiverUpdateWithoutSignedByInput, Prisma.WaiverUncheckedUpdateWithoutSignedByInput>
  create: Prisma.XOR<Prisma.WaiverCreateWithoutSignedByInput, Prisma.WaiverUncheckedCreateWithoutSignedByInput>
  where?: Prisma.WaiverWhereInput
}

export type WaiverUpdateToOneWithWhereWithoutSignedByInput = {
  where?: Prisma.WaiverWhereInput
  data: Prisma.XOR<Prisma.WaiverUpdateWithoutSignedByInput, Prisma.WaiverUncheckedUpdateWithoutSignedByInput>
}

export type WaiverUpdateWithoutSignedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  school?: Prisma.SchoolUpdateOneRequiredWithoutWaiversNestedInput
}

export type WaiverUncheckedUpdateWithoutSignedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  schoolId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WaiverCreateManySchoolInput = {
  id?: string
  title: string
  content: string
  version?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WaiverUpdateWithoutSchoolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  signedBy?: Prisma.UserWaiverUpdateManyWithoutWaiverNestedInput
}

export type WaiverUncheckedUpdateWithoutSchoolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  signedBy?: Prisma.UserWaiverUncheckedUpdateManyWithoutWaiverNestedInput
}

export type WaiverUncheckedUpdateManyWithoutSchoolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type WaiverCountOutputType
 */

export type WaiverCountOutputType = {
  signedBy: number
}

export type WaiverCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  signedBy?: boolean | WaiverCountOutputTypeCountSignedByArgs
}

/**
 * WaiverCountOutputType without action
 */
export type WaiverCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaiverCountOutputType
   */
  select?: Prisma.WaiverCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WaiverCountOutputType without action
 */
export type WaiverCountOutputTypeCountSignedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWaiverWhereInput
}


export type WaiverSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  schoolId?: boolean
  title?: boolean
  content?: boolean
  version?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  signedBy?: boolean | Prisma.Waiver$signedByArgs<ExtArgs>
  _count?: boolean | Prisma.WaiverCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waiver"]>

export type WaiverSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  schoolId?: boolean
  title?: boolean
  content?: boolean
  version?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waiver"]>

export type WaiverSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  schoolId?: boolean
  title?: boolean
  content?: boolean
  version?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waiver"]>

export type WaiverSelectScalar = {
  id?: boolean
  schoolId?: boolean
  title?: boolean
  content?: boolean
  version?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type WaiverOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "schoolId" | "title" | "content" | "version" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["waiver"]>
export type WaiverInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
  signedBy?: boolean | Prisma.Waiver$signedByArgs<ExtArgs>
  _count?: boolean | Prisma.WaiverCountOutputTypeDefaultArgs<ExtArgs>
}
export type WaiverIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
}
export type WaiverIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  school?: boolean | Prisma.SchoolDefaultArgs<ExtArgs>
}

export type $WaiverPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Waiver"
  objects: {
    school: Prisma.$SchoolPayload<ExtArgs>
    signedBy: Prisma.$UserWaiverPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    schoolId: string
    title: string
    content: string
    version: string
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["waiver"]>
  composites: {}
}

export type WaiverGetPayload<S extends boolean | null | undefined | WaiverDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WaiverPayload, S>

export type WaiverCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WaiverFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WaiverCountAggregateInputType | true
  }

export interface WaiverDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Waiver'], meta: { name: 'Waiver' } }
  /**
   * Find zero or one Waiver that matches the filter.
   * @param {WaiverFindUniqueArgs} args - Arguments to find a Waiver
   * @example
   * // Get one Waiver
   * const waiver = await prisma.waiver.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WaiverFindUniqueArgs>(args: Prisma.SelectSubset<T, WaiverFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WaiverClient<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Waiver that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WaiverFindUniqueOrThrowArgs} args - Arguments to find a Waiver
   * @example
   * // Get one Waiver
   * const waiver = await prisma.waiver.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WaiverFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WaiverFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WaiverClient<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Waiver that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaiverFindFirstArgs} args - Arguments to find a Waiver
   * @example
   * // Get one Waiver
   * const waiver = await prisma.waiver.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WaiverFindFirstArgs>(args?: Prisma.SelectSubset<T, WaiverFindFirstArgs<ExtArgs>>): Prisma.Prisma__WaiverClient<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Waiver that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaiverFindFirstOrThrowArgs} args - Arguments to find a Waiver
   * @example
   * // Get one Waiver
   * const waiver = await prisma.waiver.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WaiverFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WaiverFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WaiverClient<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Waivers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaiverFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Waivers
   * const waivers = await prisma.waiver.findMany()
   * 
   * // Get first 10 Waivers
   * const waivers = await prisma.waiver.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const waiverWithIdOnly = await prisma.waiver.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WaiverFindManyArgs>(args?: Prisma.SelectSubset<T, WaiverFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Waiver.
   * @param {WaiverCreateArgs} args - Arguments to create a Waiver.
   * @example
   * // Create one Waiver
   * const Waiver = await prisma.waiver.create({
   *   data: {
   *     // ... data to create a Waiver
   *   }
   * })
   * 
   */
  create<T extends WaiverCreateArgs>(args: Prisma.SelectSubset<T, WaiverCreateArgs<ExtArgs>>): Prisma.Prisma__WaiverClient<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Waivers.
   * @param {WaiverCreateManyArgs} args - Arguments to create many Waivers.
   * @example
   * // Create many Waivers
   * const waiver = await prisma.waiver.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WaiverCreateManyArgs>(args?: Prisma.SelectSubset<T, WaiverCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Waivers and returns the data saved in the database.
   * @param {WaiverCreateManyAndReturnArgs} args - Arguments to create many Waivers.
   * @example
   * // Create many Waivers
   * const waiver = await prisma.waiver.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Waivers and only return the `id`
   * const waiverWithIdOnly = await prisma.waiver.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WaiverCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WaiverCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Waiver.
   * @param {WaiverDeleteArgs} args - Arguments to delete one Waiver.
   * @example
   * // Delete one Waiver
   * const Waiver = await prisma.waiver.delete({
   *   where: {
   *     // ... filter to delete one Waiver
   *   }
   * })
   * 
   */
  delete<T extends WaiverDeleteArgs>(args: Prisma.SelectSubset<T, WaiverDeleteArgs<ExtArgs>>): Prisma.Prisma__WaiverClient<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Waiver.
   * @param {WaiverUpdateArgs} args - Arguments to update one Waiver.
   * @example
   * // Update one Waiver
   * const waiver = await prisma.waiver.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WaiverUpdateArgs>(args: Prisma.SelectSubset<T, WaiverUpdateArgs<ExtArgs>>): Prisma.Prisma__WaiverClient<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Waivers.
   * @param {WaiverDeleteManyArgs} args - Arguments to filter Waivers to delete.
   * @example
   * // Delete a few Waivers
   * const { count } = await prisma.waiver.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WaiverDeleteManyArgs>(args?: Prisma.SelectSubset<T, WaiverDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Waivers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaiverUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Waivers
   * const waiver = await prisma.waiver.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WaiverUpdateManyArgs>(args: Prisma.SelectSubset<T, WaiverUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Waivers and returns the data updated in the database.
   * @param {WaiverUpdateManyAndReturnArgs} args - Arguments to update many Waivers.
   * @example
   * // Update many Waivers
   * const waiver = await prisma.waiver.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Waivers and only return the `id`
   * const waiverWithIdOnly = await prisma.waiver.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WaiverUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WaiverUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Waiver.
   * @param {WaiverUpsertArgs} args - Arguments to update or create a Waiver.
   * @example
   * // Update or create a Waiver
   * const waiver = await prisma.waiver.upsert({
   *   create: {
   *     // ... data to create a Waiver
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Waiver we want to update
   *   }
   * })
   */
  upsert<T extends WaiverUpsertArgs>(args: Prisma.SelectSubset<T, WaiverUpsertArgs<ExtArgs>>): Prisma.Prisma__WaiverClient<runtime.Types.Result.GetResult<Prisma.$WaiverPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Waivers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaiverCountArgs} args - Arguments to filter Waivers to count.
   * @example
   * // Count the number of Waivers
   * const count = await prisma.waiver.count({
   *   where: {
   *     // ... the filter for the Waivers we want to count
   *   }
   * })
  **/
  count<T extends WaiverCountArgs>(
    args?: Prisma.Subset<T, WaiverCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WaiverCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Waiver.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaiverAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WaiverAggregateArgs>(args: Prisma.Subset<T, WaiverAggregateArgs>): Prisma.PrismaPromise<GetWaiverAggregateType<T>>

  /**
   * Group by Waiver.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaiverGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WaiverGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WaiverGroupByArgs['orderBy'] }
      : { orderBy?: WaiverGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WaiverGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWaiverGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Waiver model
 */
readonly fields: WaiverFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Waiver.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WaiverClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  school<T extends Prisma.SchoolDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SchoolDefaultArgs<ExtArgs>>): Prisma.Prisma__SchoolClient<runtime.Types.Result.GetResult<Prisma.$SchoolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  signedBy<T extends Prisma.Waiver$signedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Waiver$signedByArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserWaiverPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Waiver model
 */
export interface WaiverFieldRefs {
  readonly id: Prisma.FieldRef<"Waiver", 'String'>
  readonly schoolId: Prisma.FieldRef<"Waiver", 'String'>
  readonly title: Prisma.FieldRef<"Waiver", 'String'>
  readonly content: Prisma.FieldRef<"Waiver", 'String'>
  readonly version: Prisma.FieldRef<"Waiver", 'String'>
  readonly isActive: Prisma.FieldRef<"Waiver", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Waiver", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Waiver", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Waiver findUnique
 */
export type WaiverFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * Filter, which Waiver to fetch.
   */
  where: Prisma.WaiverWhereUniqueInput
}

/**
 * Waiver findUniqueOrThrow
 */
export type WaiverFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * Filter, which Waiver to fetch.
   */
  where: Prisma.WaiverWhereUniqueInput
}

/**
 * Waiver findFirst
 */
export type WaiverFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * Filter, which Waiver to fetch.
   */
  where?: Prisma.WaiverWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Waivers to fetch.
   */
  orderBy?: Prisma.WaiverOrderByWithRelationInput | Prisma.WaiverOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Waivers.
   */
  cursor?: Prisma.WaiverWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Waivers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Waivers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Waivers.
   */
  distinct?: Prisma.WaiverScalarFieldEnum | Prisma.WaiverScalarFieldEnum[]
}

/**
 * Waiver findFirstOrThrow
 */
export type WaiverFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * Filter, which Waiver to fetch.
   */
  where?: Prisma.WaiverWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Waivers to fetch.
   */
  orderBy?: Prisma.WaiverOrderByWithRelationInput | Prisma.WaiverOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Waivers.
   */
  cursor?: Prisma.WaiverWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Waivers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Waivers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Waivers.
   */
  distinct?: Prisma.WaiverScalarFieldEnum | Prisma.WaiverScalarFieldEnum[]
}

/**
 * Waiver findMany
 */
export type WaiverFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * Filter, which Waivers to fetch.
   */
  where?: Prisma.WaiverWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Waivers to fetch.
   */
  orderBy?: Prisma.WaiverOrderByWithRelationInput | Prisma.WaiverOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Waivers.
   */
  cursor?: Prisma.WaiverWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Waivers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Waivers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Waivers.
   */
  distinct?: Prisma.WaiverScalarFieldEnum | Prisma.WaiverScalarFieldEnum[]
}

/**
 * Waiver create
 */
export type WaiverCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * The data needed to create a Waiver.
   */
  data: Prisma.XOR<Prisma.WaiverCreateInput, Prisma.WaiverUncheckedCreateInput>
}

/**
 * Waiver createMany
 */
export type WaiverCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Waivers.
   */
  data: Prisma.WaiverCreateManyInput | Prisma.WaiverCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Waiver createManyAndReturn
 */
export type WaiverCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * The data used to create many Waivers.
   */
  data: Prisma.WaiverCreateManyInput | Prisma.WaiverCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Waiver update
 */
export type WaiverUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * The data needed to update a Waiver.
   */
  data: Prisma.XOR<Prisma.WaiverUpdateInput, Prisma.WaiverUncheckedUpdateInput>
  /**
   * Choose, which Waiver to update.
   */
  where: Prisma.WaiverWhereUniqueInput
}

/**
 * Waiver updateMany
 */
export type WaiverUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Waivers.
   */
  data: Prisma.XOR<Prisma.WaiverUpdateManyMutationInput, Prisma.WaiverUncheckedUpdateManyInput>
  /**
   * Filter which Waivers to update
   */
  where?: Prisma.WaiverWhereInput
  /**
   * Limit how many Waivers to update.
   */
  limit?: number
}

/**
 * Waiver updateManyAndReturn
 */
export type WaiverUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * The data used to update Waivers.
   */
  data: Prisma.XOR<Prisma.WaiverUpdateManyMutationInput, Prisma.WaiverUncheckedUpdateManyInput>
  /**
   * Filter which Waivers to update
   */
  where?: Prisma.WaiverWhereInput
  /**
   * Limit how many Waivers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Waiver upsert
 */
export type WaiverUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * The filter to search for the Waiver to update in case it exists.
   */
  where: Prisma.WaiverWhereUniqueInput
  /**
   * In case the Waiver found by the `where` argument doesn't exist, create a new Waiver with this data.
   */
  create: Prisma.XOR<Prisma.WaiverCreateInput, Prisma.WaiverUncheckedCreateInput>
  /**
   * In case the Waiver was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WaiverUpdateInput, Prisma.WaiverUncheckedUpdateInput>
}

/**
 * Waiver delete
 */
export type WaiverDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
  /**
   * Filter which Waiver to delete.
   */
  where: Prisma.WaiverWhereUniqueInput
}

/**
 * Waiver deleteMany
 */
export type WaiverDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Waivers to delete
   */
  where?: Prisma.WaiverWhereInput
  /**
   * Limit how many Waivers to delete.
   */
  limit?: number
}

/**
 * Waiver.signedBy
 */
export type Waiver$signedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWaiver
   */
  select?: Prisma.UserWaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWaiver
   */
  omit?: Prisma.UserWaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWaiverInclude<ExtArgs> | null
  where?: Prisma.UserWaiverWhereInput
  orderBy?: Prisma.UserWaiverOrderByWithRelationInput | Prisma.UserWaiverOrderByWithRelationInput[]
  cursor?: Prisma.UserWaiverWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserWaiverScalarFieldEnum | Prisma.UserWaiverScalarFieldEnum[]
}

/**
 * Waiver without action
 */
export type WaiverDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Waiver
   */
  select?: Prisma.WaiverSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Waiver
   */
  omit?: Prisma.WaiverOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaiverInclude<ExtArgs> | null
}
